FROM node:22-alpine AS build
WORKDIR /app
RUN corepack enable
COPY frontend/package.json frontend/pnpm-lock.yaml frontend/pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile
COPY frontend ./
RUN pnpm run build
FROM nginxinc/nginx-unprivileged:1.27-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY deploy/cloud-run/nginx.conf /etc/nginx/conf.d/default.conf
ENV PORT=8080
CMD ["sh","-c","sed -i s/PORT_PLACEHOLDER/${PORT}/g /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;' "]
