from __future__ import annotations
from datetime import datetime, timezone
from typing import Any
from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column
from ..database import Base
def now(): return datetime.now(timezone.utc)
class Incident(Base):
    __tablename__="incidents"; id:Mapped[int]=mapped_column(primary_key=True); title:Mapped[str]=mapped_column(String(200)); description:Mapped[str]=mapped_column(Text,default=""); severity:Mapped[str]=mapped_column(String(20),default="SEV2"); source:Mapped[str]=mapped_column(String(50),default="demo"); service_name:Mapped[str]=mapped_column(String(100),default="sentinel-shop"); status:Mapped[str]=mapped_column(String(30),default="active"); started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); detected_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); resolved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); current_state:Mapped[str]=mapped_column(String(40),default="NEW"); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
class EvidenceItem(Base):
    __tablename__="evidence_items"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); evidence_type:Mapped[str]=mapped_column(String(30)); source:Mapped[str]=mapped_column(String(255)); content:Mapped[str]=mapped_column(Text); summary:Mapped[str]=mapped_column(Text); timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); relevance_score:Mapped[float]=mapped_column(Float,default=0.5); metadata_json:Mapped[dict[str,Any]]=mapped_column(JSON,default=dict)
class Hypothesis(Base):
    __tablename__="hypotheses"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); title:Mapped[str]=mapped_column(String(250)); explanation:Mapped[str]=mapped_column(Text); evidence_for:Mapped[list]=mapped_column(JSON); evidence_against:Mapped[list]=mapped_column(JSON); confidence:Mapped[float]=mapped_column(Float); rank:Mapped[int]=mapped_column(Integer); status:Mapped[str]=mapped_column(String(30),default="proposed")
class ReproductionAttempt(Base):
    __tablename__="reproduction_attempts"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); command:Mapped[str]=mapped_column(Text); test_file:Mapped[str]=mapped_column(Text); result:Mapped[str]=mapped_column(String(30)); stdout:Mapped[str]=mapped_column(Text,default=""); stderr:Mapped[str]=mapped_column(Text,default=""); duration:Mapped[float]=mapped_column(Float,default=0); exit_code:Mapped[int]=mapped_column(Integer)
class PatchCandidate(Base):
    __tablename__="patch_candidates"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); hypothesis_id:Mapped[int]=mapped_column(ForeignKey("hypotheses.id")); diff:Mapped[str]=mapped_column(Text); explanation:Mapped[str]=mapped_column(Text); files_changed:Mapped[list]=mapped_column(JSON); risk_score:Mapped[float]=mapped_column(Float); status:Mapped[str]=mapped_column(String(30),default="proposed")
class VerificationRun(Base):
    __tablename__="verification_runs"; id:Mapped[int]=mapped_column(primary_key=True); patch_candidate_id:Mapped[int]=mapped_column(ForeignKey("patch_candidates.id")); test_type:Mapped[str]=mapped_column(String(40)); command:Mapped[str]=mapped_column(Text); passed:Mapped[bool]=mapped_column(Boolean); stdout:Mapped[str]=mapped_column(Text,default=""); stderr:Mapped[str]=mapped_column(Text,default=""); duration:Mapped[float]=mapped_column(Float,default=0); exit_code:Mapped[int]=mapped_column(Integer)
class ApprovalRequest(Base):
    __tablename__="approval_requests"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); requested_action:Mapped[str]=mapped_column(String(100)); summary:Mapped[str]=mapped_column(Text); risk_level:Mapped[str]=mapped_column(String(20)); approved:Mapped[bool|None]=mapped_column(Boolean); approved_by:Mapped[str|None]=mapped_column(String(100)); approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class AuditEvent(Base):
    __tablename__="audit_events"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); event_type:Mapped[str]=mapped_column(String(80)); actor:Mapped[str]=mapped_column(String(100)); input_json:Mapped[dict]=mapped_column(JSON,default=dict); output_json:Mapped[dict]=mapped_column(JSON,default=dict); timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class PullRequestRecord(Base):
    __tablename__="pull_request_records"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); branch_name:Mapped[str]=mapped_column(String(150)); commit_sha:Mapped[str]=mapped_column(String(64)); title:Mapped[str]=mapped_column(String(250)); description:Mapped[str]=mapped_column(Text); diff:Mapped[str]=mapped_column(Text); status:Mapped[str]=mapped_column(String(30),default="draft"); external_url:Mapped[str|None]=mapped_column(String(500))

# Finale extension tables deliberately store signed/validated structured artifacts as JSON.  This
# keeps the hackathon SQLite path migration-free while remaining portable to PostgreSQL.
class TwinManifest(Base):
    __tablename__="twin_manifests"; id:Mapped[int]=mapped_column(primary_key=True); twin_id:Mapped[str]=mapped_column(String(64),unique=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); source_commit:Mapped[str]=mapped_column(String(64)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); runtime_version:Mapped[str]=mapped_column(String(80)); operating_system:Mapped[str]=mapped_column(String(120)); dependency_lock_hash:Mapped[str]=mapped_column(String(64)); configuration_hash:Mapped[str]=mapped_column(String(64)); input_fixture_hash:Mapped[str]=mapped_column(String(64)); random_seed:Mapped[int]=mapped_column(Integer); network_policy:Mapped[str]=mapped_column(String(40),default="disabled"); resource_limits:Mapped[dict]=mapped_column(JSON,default=dict); command_allowlist:Mapped[list]=mapped_column(JSON,default=list); protected_paths:Mapped[list]=mapped_column(JSON,default=list); evidence_ids:Mapped[list]=mapped_column(JSON,default=list); environment_fingerprint:Mapped[str]=mapped_column(String(64)); manifest_hash:Mapped[str]=mapped_column(String(64),unique=True)
class ReplayRun(Base):
    __tablename__="replay_runs"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); twin_id:Mapped[str]=mapped_column(String(64)); candidate_id:Mapped[str|None]=mapped_column(String(40)); attempt:Mapped[int]=mapped_column(Integer); request_json:Mapped[dict]=mapped_column(JSON); response_json:Mapped[dict]=mapped_column(JSON); exit_status:Mapped[int]=mapped_column(Integer); logs_json:Mapped[list]=mapped_column(JSON); traces_json:Mapped[list]=mapped_column(JSON); metrics_json:Mapped[dict]=mapped_column(JSON); duration_ms:Mapped[float]=mapped_column(Float); resource_usage:Mapped[dict]=mapped_column(JSON); test_output:Mapped[str]=mapped_column(Text); reproduced:Mapped[bool]=mapped_column(Boolean); deterministic_hash:Mapped[str]=mapped_column(String(64))
class RepairCandidate(Base):
    __tablename__="repair_candidates"; id:Mapped[int]=mapped_column(primary_key=True); candidate_id:Mapped[str]=mapped_column(String(40)); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); hypothesis_id:Mapped[int|None]=mapped_column(ForeignKey("hypotheses.id")); rationale:Mapped[str]=mapped_column(Text); files_changed:Mapped[list]=mapped_column(JSON); lines_added:Mapped[int]=mapped_column(Integer); lines_removed:Mapped[int]=mapped_column(Integer); protected_path_status:Mapped[str]=mapped_column(String(30)); generated_regression_test:Mapped[str]=mapped_column(Text); expected_behavior:Mapped[str]=mapped_column(Text); assumptions:Mapped[list]=mapped_column(JSON); known_risks:Mapped[list]=mapped_column(JSON); diff:Mapped[str]=mapped_column(Text); creation_method:Mapped[str]=mapped_column(String(50)); score:Mapped[float]=mapped_column(Float,default=0); eligible:Mapped[bool]=mapped_column(Boolean,default=False); recommendation_reason:Mapped[str]=mapped_column(Text,default="")
class CandidateVerification(Base):
    __tablename__="candidate_verifications"; id:Mapped[int]=mapped_column(primary_key=True); candidate_id:Mapped[str]=mapped_column(String(40)); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); gate:Mapped[str]=mapped_column(String(60)); mandatory:Mapped[bool]=mapped_column(Boolean); passed:Mapped[bool]=mapped_column(Boolean); reduced_assurance:Mapped[bool]=mapped_column(Boolean,default=False); duration_ms:Mapped[float]=mapped_column(Float); details:Mapped[str]=mapped_column(Text); evidence_ids:Mapped[list]=mapped_column(JSON,default=list)
class CounterfactualScenario(Base):
    __tablename__="counterfactual_scenarios"; id:Mapped[int]=mapped_column(primary_key=True); scenario_id:Mapped[str]=mapped_column(String(60)); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); name:Mapped[str]=mapped_column(String(120)); inputs:Mapped[dict]=mapped_column(JSON); assumptions:Mapped[list]=mapped_column(JSON,default=list)
class ScenarioResult(Base):
    __tablename__="scenario_results"; id:Mapped[int]=mapped_column(primary_key=True); scenario_id:Mapped[str]=mapped_column(String(60)); candidate_id:Mapped[str]=mapped_column(String(40)); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); outcome:Mapped[str]=mapped_column(String(20)); error_type:Mapped[str|None]=mapped_column(String(80)); latency_ms:Mapped[float]=mapped_column(Float); reproduced:Mapped[bool]=mapped_column(Boolean); candidate_success:Mapped[bool]=mapped_column(Boolean); new_failure:Mapped[bool]=mapped_column(Boolean); confidence_label:Mapped[str]=mapped_column(String(20)); evidence_ids:Mapped[list]=mapped_column(JSON,default=list); details:Mapped[dict]=mapped_column(JSON,default=dict)
class BlastRadiusEstimate(Base):
    __tablename__="blast_radius_estimates"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); candidate_id:Mapped[str]=mapped_column(String(40)); score:Mapped[float]=mapped_column(Float); confidence_label:Mapped[str]=mapped_column(String(20)); modified_components:Mapped[list]=mapped_column(JSON); transitive_components:Mapped[list]=mapped_column(JSON); covered_workflows:Mapped[list]=mapped_column(JSON); uncovered_workflows:Mapped[list]=mapped_column(JSON); critical_paths:Mapped[list]=mapped_column(JSON); customer_impact:Mapped[str]=mapped_column(Text); graph_json:Mapped[dict]=mapped_column(JSON); evidence_ids:Mapped[list]=mapped_column(JSON,default=list)
class EvidenceLink(Base):
    __tablename__="evidence_links"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); claim_type:Mapped[str]=mapped_column(String(50)); claim_id:Mapped[str]=mapped_column(String(80)); claim:Mapped[str]=mapped_column(Text); evidence_ids:Mapped[list]=mapped_column(JSON); missing_evidence:Mapped[list]=mapped_column(JSON,default=list); confidence_label:Mapped[str]=mapped_column(String(20)); rationale:Mapped[str]=mapped_column(Text)
class RedTeamReview(Base):
    __tablename__="red_team_reviews"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); candidate_id:Mapped[str]=mapped_column(String(40)); advocate_case:Mapped[str]=mapped_column(Text); challenges:Mapped[list]=mapped_column(JSON); deterministic_verdict:Mapped[str]=mapped_column(String(30)); evidence_ids:Mapped[list]=mapped_column(JSON,default=list); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class AuditChainEvent(Base):
    __tablename__="audit_chain_events"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); sequence:Mapped[int]=mapped_column(Integer); event_type:Mapped[str]=mapped_column(String(80)); payload_json:Mapped[dict]=mapped_column(JSON); previous_hash:Mapped[str]=mapped_column(String(64)); event_hash:Mapped[str]=mapped_column(String(64)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class IncidentPackage(Base):
    __tablename__="incident_packages"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); format_version:Mapped[str]=mapped_column(String(20),default="1.0"); package_json:Mapped[dict]=mapped_column(JSON); artifact_hashes:Mapped[dict]=mapped_column(JSON); first_event_hash:Mapped[str]=mapped_column(String(64)); final_audit_hash:Mapped[str]=mapped_column(String(64)); package_hash:Mapped[str]=mapped_column(String(64)); verified:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
