import type {Audit,AuditPackage,Evidence,EvidenceLink,Health,Incident,Hypothesis,NexusAgent,NexusAuditV1,NexusEvidenceV1,NexusRun,NexusTelemetry,NexusTwin,Patch,PullRequest,ReplayRun,ScenarioResult,Scorecard,Tournament,TwinManifest,Verification} from '../types'
const BASE=(import.meta.env.VITE_API_BASE_URL||'').replace(/\/$/,'')
async function req<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(`${BASE}${path}`,{headers:{'Content-Type':'application/json'},...init});if(!r.ok)throw new Error(`Backend request failed (${r.status}). Check port 8000 and run make demo.`);return r.json()}
export const api={nexus:(load=1,capacity=12000)=>req<NexusTwin>(`/api/nexus/operational-twin?load_multiplier=${load}&redis_capacity=${capacity}`),incidents:()=>req<Incident[]>('/api/incidents'),seed:()=>req<{ids?:number[]}>('/api/demo/seed',{method:'POST'}),reset:()=>req('/api/demo/reset',{method:'POST'}),trigger:()=>req<Incident>('/api/demo/trigger-incident',{method:'POST'}),health:()=>req<Health>('/health'),get:(id:number)=>req<Incident>(`/api/incidents/${id}`),evidence:(id:number)=>req<Evidence[]>(`/api/incidents/${id}/evidence`),hypotheses:(id:number)=>req<Hypothesis[]>(`/api/incidents/${id}/hypotheses`),timeline:(id:number)=>req<Audit[]>(`/api/incidents/${id}/timeline`),verification:(id:number)=>req<Verification[]>(`/api/incidents/${id}/verification`),patches:(id:number)=>req<Patch[]>(`/api/incidents/${id}/patches`),prs:(id:number)=>req<PullRequest[]>(`/api/incidents/${id}/pull-requests`),twin:(id:number)=>req<TwinManifest>(`/api/incidents/${id}/digital-twin`),replays:(id:number)=>req<ReplayRun[]>(`/api/incidents/${id}/replays`),tournament:(id:number)=>req<Tournament>(`/api/incidents/${id}/repair-tournament`),counterfactuals:(id:number)=>req<ScenarioResult[]>(`/api/incidents/${id}/counterfactuals`),evidenceLinks:(id:number)=>req<EvidenceLink[]>(`/api/incidents/${id}/evidence-links`),scorecard:(id:number)=>req<Scorecard>(`/api/incidents/${id}/scorecard`),auditPackage:(id:number)=>req<AuditPackage>(`/api/incidents/${id}/audit-package`),downloadUrl:(id:number,kind:'json'|'report'|'bundle')=>`${BASE}/api/incidents/${id}/audit-package${kind==='json'?'':`/${kind}`}`,action:(id:number,a:string,body?:object)=>req(`/api/incidents/${id}/${a}`,{method:'POST',body:body?JSON.stringify(body):undefined})}
export const nexusApi={
 bootstrap:()=>req<NexusRun>('/api/v1/demo/bootstrap',{method:'POST'}),
 workflows:()=>req<NexusRun[]>('/api/v1/workflows'),
 seed:()=>req<NexusRun>('/api/v1/demo/seed',{method:'POST'}),
 reset:()=>req('/api/v1/demo/reset',{method:'POST'}),
 runAll:(id:number)=>req<NexusRun>(`/api/v1/workflows/${id}/run-all`,{method:'POST'}),
 create:(controls:Record<string,unknown>)=>req<NexusRun>('/api/v1/workflows',{method:'POST',body:JSON.stringify({name:'Payment Service capacity forecast',controls})}),
 telemetry:(id:number)=>req<NexusTelemetry[]>(`/api/v1/telemetry?run_id=${id}`),
 evidence:(id:number)=>req<NexusEvidenceV1[]>(`/api/v1/workflows/${id}/evidence`),
 uploadEvidence:(id:number,payload:{filename:string;category:string;content:string})=>req<NexusEvidenceV1>(`/api/v1/workflows/${id}/evidence/upload`,{method:'POST',body:JSON.stringify(payload)}),
 timeline:(id:number)=>req<NexusAuditV1[]>(`/api/v1/workflows/${id}/timeline`),
 agents:(id:number)=>req<NexusAgent[]>(`/api/v1/workflows/${id}/agents`),
 approve:(id:number)=>req<Record<string,unknown>>(`/api/v1/workflows/${id}/approve`,{method:'POST',body:JSON.stringify({actor:'finale-judge',decision:'approve',rationale:'Reviewed all deterministic gates and evidence references.'})}),
 reject:(id:number)=>req<Record<string,unknown>>(`/api/v1/workflows/${id}/reject`,{method:'POST',body:JSON.stringify({actor:'finale-judge',decision:'reject',rationale:'Human reviewer rejected the recommendation.'})}),
 downloadEvidence:async(id:number)=>{const response=await fetch(`${BASE}/api/v1/workflows/${id}/export`);if(!response.ok)throw new Error(response.status===409?'Evidence ZIP has already been downloaded and revoked.':`Evidence export failed (${response.status}).`);const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`sentinelops-nexus-${id}.zip`;anchor.click();URL.revokeObjectURL(url)},
}
