import {ARCHITECTURE_DOMAINS} from './types';
import type {ArchitectureComponent,ArchitectureDomain,ArchitectureStatus,CloudRunServiceView,IntegrationHealth} from './types';
export {ARCHITECTURE_DOMAINS};

type Seed={title:string;purpose:string;status?:ArchitectureStatus;integrationKey?:string;cloud?:string[];boundary?:ArchitectureComponent['boundary'];related?:string[];inputs?:string[];outputs?:string[];missing?:string[]};
const slug=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const domainDefaults:Record<ArchitectureDomain,{what:string;why:string;authority:string;security:string[];fallback:string}>={
 'Product Experience':{what:'Presents backend-derived operational evidence through accessible product workflows.',why:'Operators need one coherent surface for prediction, evidence, and governed decisions.',authority:'Presentation only; the frontend never authorizes or executes workflow transitions.',security:['Strict API boundary','No server credentials bundled in frontend assets'],fallback:'Shows unavailable or fallback state without inventing success.'},
 'API and Authority':{what:'Validates requests, persists state, and enforces workflow and authorization policy.',why:'A deterministic backend authority prevents models or UI state from bypassing governance.',authority:'Authoritative for validated workflow state, authorization, safety gates, audit, and export.',security:['Pydantic validation','Backend RBAC','Request limits','Safe errors'],fallback:'Fails closed and preserves the previous authoritative state.'},
 'Agent Layer':{what:'Executes one bounded workforce responsibility using persisted inputs and outputs.',why:'Typed, auditable specialization makes each operational step inspectable and retryable.',authority:'May propose or verify within permitted states; cannot approve or execute production changes.',security:['Permitted-state validation','Audit event on execution','No hidden chain-of-thought exposure'],fallback:'Returns structured failure or bounded local output according to policy.'},
 'Agent Protocols':{what:'Coordinates typed agent work and controlled tool access.',why:'Explicit protocols make delegation, evidence exchange, retries, and tool boundaries traceable.',authority:'Carries orchestration intent only; backend policy remains authoritative.',security:['Typed schemas','Correlation and trace IDs','Authentication and authorization'],fallback:'Uses a bounded local adapter or rejects unsupported operations.'},
 'AI Layer':{what:'Develops, evaluates, generates, or critiques evidence-grounded explanations.',why:'AI improves synthesis while deterministic services retain operational authority.',authority:'Advisory only; cannot approve, change eligibility, mutate workflow state, or execute production actions.',security:['Strict output schema','Evidence references','Prompt versioning','Prohibited-action checks'],fallback:'Uses explicit deterministic fallback and labels it as fallback.'},
 'Deterministic Intelligence':{what:'Calculates reproducible forecasts, scenarios, rankings, gates, verification, and impact.',why:'Operational eligibility must be explainable, repeatable, and independent of model narrative.',authority:'Authoritative for calculated results and mandatory eligibility gates.',security:['Fixed seed','Versioned assumptions','Content hashes','Bounded inputs'],fallback:'Rejects invalid inputs or uses the documented deterministic baseline.'},
 'Data and Events':{what:'Persists transactional evidence or transports typed analytical and event records.',why:'Decisions require durable evidence, replayable provenance, and separated analytical storage.',authority:'Transactional backend state remains authoritative; analytical stores never decide workflow state.',security:['Redaction','Idempotency','Schema versioning','Audit integration'],fallback:'Queues, retries, dead-letters, or retains local persistence without claiming managed delivery.'},
 'Google Cloud Runtime':{what:'Builds, stores, deploys, configures, and identifies independently packageable services.',why:'Managed runtime boundaries support repeatable deployment and least-privilege operation.',authority:'Hosting and identity only; no component gains production-change authority.',security:['Least-privilege IAM','Service identities','Secret references','ADC'],fallback:'Requires authenticated cloud evidence; local operation remains available.'},
 'Observability':{what:'Propagates and exports structured operational and AI telemetry.',why:'Correlation makes multi-service evidence and failures diagnosable end to end.',authority:'Observes but cannot mutate workflows or infrastructure.',security:['Secret redaction','Structured logs','Trace-context propagation'],fallback:'Retains local structured telemetry when cloud exporters are unavailable.'},
 'Participant Boundary':{what:'Surfaces an explicitly bounded participant integration contract.',why:'Unavailable participant access must be visible without fabricating SDK or runtime proof.',authority:'Read-only status boundary with no workflow, approval, gate, or infrastructure authority.',security:['No invented endpoint','No credentials exposed','No state mutation'],fallback:'Returns the documented participant-access blocker.'}
};

const seeds:Record<ArchitectureDomain,Seed[]>={
 'Product Experience':[
  {title:'React Frontend',purpose:'Deliver the responsive SentinelOps Nexus product shell.'},{title:'Command Centre',purpose:'Operate the deterministic Digital Twin and inspect results.'},{title:'Judge Demo',purpose:'Explain the end-to-end workflow through interactive evidence.'},{title:'AI Workforce',purpose:'Expose clickable backend-driven agent workspaces.'},{title:'Approval Workspace',purpose:'Collect verified role, decision, and mandatory rationale.',boundary:'human'},{title:'Evidence Workspace',purpose:'Inspect persisted evidence, audit, verification, and exports.'}],
 'API and Authority':[
  {title:'API Gateway',purpose:'Provide the controlled HTTP entry point.',cloud:['Cloud Run'] ,boundary:'authenticated'},{title:'FastAPI Backend',purpose:'Host typed workflow and evidence APIs.',cloud:['Cloud Run']},{title:'Workflow State Engine',purpose:'Own validated workflow transitions.',boundary:'deterministic'},{title:'RBAC',purpose:'Enforce role permissions on the server.',integrationKey:'OAuth2/JWT',boundary:'authenticated'},{title:'JWT Validation',purpose:'Validate signed, short-lived role tokens.',integrationKey:'OAuth2/JWT',boundary:'authenticated'},{title:'Approval Authorization',purpose:'Permit only qualified human decisions with rationale.',boundary:'human'},{title:'Audit Chain',purpose:'Append tamper-evident SHA-256-linked events.',boundary:'deterministic'},{title:'Evidence Export',purpose:'Generate the governed Evidence ZIP and manifest.',boundary:'deterministic'}],
 'Agent Layer':[
  {title:'Nexus Orchestrator',purpose:'Coordinate the bounded workforce sequence.'},{title:'Observer Agent',purpose:'Persist the current operational state.'},{title:'Evidence Agent',purpose:'Collect and link source evidence.'},{title:'Process Discovery Agent',purpose:'Discover service topology and dependencies.'},{title:'Prediction Agent',purpose:'Invoke the deterministic Redis forecast.'},{title:'Digital Twin Agent',purpose:'Create the version-locked Twin manifest.'},{title:'Simulation Agent',purpose:'Replay twelve deterministic scenarios.'},{title:'Optimization Agent',purpose:'Compare FAST, SAFE, and OPTIMAL candidates.'},{title:'Verification Agent',purpose:'Verify technical and approver readiness without approving.',boundary:'deterministic'},{title:'Business Impact Agent',purpose:'Calculate operational business exposure.'},{title:'Executive Agent',purpose:'Generate an evidence-backed recommendation after verification.'}],
 'Agent Protocols':[
  {title:'Google ADK boundary',purpose:'Expose an ADK-compatible agent registry and orchestration boundary.',status:'LOCAL_ADAPTER_ONLY',integrationKey:'ADK'},{title:'A2A messages',purpose:'Persist typed delegation, progress, artifact, and completion messages.',integrationKey:'A2A'},{title:'MCP gateway',purpose:'Provide authenticated, controlled operational tools.',integrationKey:'MCP',boundary:'authenticated'}],
 'AI Layer':[
  {title:'Google AI Studio',purpose:'Develop and evaluate versioned prompts outside runtime.',integrationKey:'Google AI Studio'},{title:'Prompt Management',purpose:'Version CRISPE context, schemas, tools, and refusal conditions.'},{title:'Prompt Evaluation',purpose:'Test evidence grounding, schema compliance, and prohibited actions.'},{title:'Gemini Enterprise Agent Platform',purpose:'Synthesize evidence, contradictions, scenarios, and executive narrative.',integrationKey:'Gemini'},{title:'Gemma Private Policy Review Engine',purpose:'Critique policy consistency and evidence completeness.',integrationKey:'Gemma'},{title:'Deterministic fallback',purpose:'Preserve a bounded working path when managed AI is unavailable.',status:'FALLBACK_ACTIVE'}],
 'Deterministic Intelligence':[
  {title:'Redis Forecast Engine',purpose:'Calculate bounded safe-capacity and impact timing.',boundary:'deterministic'},{title:'Digital Twin Engine',purpose:'Build a content-hashed operational model.',boundary:'deterministic'},{title:'Scenario Engine',purpose:'Replay twelve fixed counterfactuals.',boundary:'deterministic'},{title:'Optimization Engine',purpose:'Score candidates while preserving eligibility override.',boundary:'deterministic'},{title:'Mandatory Safety Gates',purpose:'Enforce failover, performance, policy, evidence, and audit gates.',boundary:'deterministic'},{title:'Verification Engine',purpose:'Persist technical and approver qualification checks.',boundary:'deterministic'},{title:'Business Impact Engine',purpose:'Calculate documented customer and revenue exposure estimates.',boundary:'deterministic'}],
 'Data and Events':[
  {title:'Transactional SQLite',purpose:'Persist authoritative local transactional workflow state.'},{title:'BigQuery',purpose:'Store analytical and historical evidence, never transactional authority.',integrationKey:'BigQuery',cloud:['BigQuery'],missing:['Authenticated write/read row ID']},{title:'Pub/Sub',purpose:'Carry typed asynchronous events with retry and trace metadata.',integrationKey:'Pub/Sub',cloud:['Pub/Sub'],missing:['Authenticated publish/consume message ID']},{title:'Evidence ZIP',purpose:'Package portable decision evidence.'},{title:'SHA-256 manifest',purpose:'Verify every exported package member.',boundary:'deterministic'},{title:'Audit export',purpose:'Copy redacted audit analytics without changing source authority.'}],
 'Google Cloud Runtime':[
  {title:'Cloud Build',purpose:'Build commit-addressed service images.',integrationKey:'Cloud Run',cloud:['Cloud Build']},{title:'Artifact Registry',purpose:'Store deployable container images.',integrationKey:'Cloud Run',cloud:['Artifact Registry']},{title:'Cloud Run',purpose:'Host nine independently packageable services.',integrationKey:'Cloud Run',cloud:['Cloud Run']},{title:'Secret Manager',purpose:'Inject server-side secret references.',integrationKey:'Cloud Run',cloud:['Secret Manager'],boundary:'authenticated'},{title:'IAM',purpose:'Enforce least-privilege service and operator permissions.',integrationKey:'Cloud Run',cloud:['IAM'],boundary:'authenticated'},{title:'Service Accounts',purpose:'Give each service a bounded runtime identity.',integrationKey:'Cloud Run',cloud:['IAM'],boundary:'authenticated'},{title:'Application Default Credentials',purpose:'Provide keyless Google client authentication.',integrationKey:'Cloud Run',cloud:['ADC'],boundary:'authenticated'}],
 'Observability':[
  {title:'OpenTelemetry',purpose:'Instrument HTTP, agents, protocols, models, and decisions.',integrationKey:'OpenTelemetry'},{title:'Cloud Logging',purpose:'Receive redacted structured runtime logs.',integrationKey:'OpenTelemetry',cloud:['Cloud Logging']},{title:'Cloud Monitoring',purpose:'Receive service and application measurements.',integrationKey:'OpenTelemetry',cloud:['Cloud Monitoring']},{title:'Cloud Trace',purpose:'Receive distributed trace spans.',integrationKey:'OpenTelemetry',cloud:['Cloud Trace'],missing:['Authenticated exported trace ID']},{title:'Correlation IDs',purpose:'Link operations across agent, event, and evidence flows.'},{title:'Trace IDs',purpose:'Link distributed request and model spans.'},{title:'Model invocation IDs',purpose:'Identify bounded AI calls without storing private reasoning.'}],
 'Participant Boundary':[
  {title:'Antigravity integration boundary',purpose:'Represent participant access truthfully without inventing a runtime.',status:'BLOCKED_BY_PARTICIPANT_ACCESS',integrationKey:'Antigravity',missing:['Official participant documentation, SDK, endpoint, and credentials']}]
};

export const ARCHITECTURE_COMPONENTS:ArchitectureComponent[]=Object.entries(seeds).flatMap(([domain,items])=>items.map(seed=>{const d=domain as ArchitectureDomain;const defaults=domainDefaults[d];return {
 id:slug(seed.title),title:seed.title,domain:d,purpose:seed.purpose,whatItDoes:defaults.what,whyItMatters:defaults.why,
 inputs:seed.inputs??['Typed backend or configuration artifacts'],outputs:seed.outputs??['Structured status, evidence, or workflow artifact'],authority:defaults.authority,
 defaultStatus:seed.status??'VERIFIED_LOCAL',integrationKey:seed.integrationKey,implemented:['Typed repository implementation','Tested local contract','Explicit safety boundary'],
 missingEvidence:seed.missing??(seed.integrationKey?['Authenticated managed-runtime evidence where applicable']:[]),evidence:['Repository source','Automated tests','Backend integration-health status'],
 googleCloudServices:seed.cloud??[],security:defaults.security,failureBehavior:'Fails safely with explicit unavailable or failed status.',fallback:defaults.fallback,
 related:seed.related??[],judgeTakeaway:`${seed.title} contributes to ${d.toLowerCase()} without crossing the production-action boundary.`,boundary:seed.boundary
} as ArchitectureComponent}));

for(const component of ARCHITECTURE_COMPONENTS){
 if(!component.related.length){
  component.related=ARCHITECTURE_COMPONENTS.filter(candidate=>candidate.domain===component.domain&&candidate.id!==component.id).slice(0,3).map(candidate=>candidate.title);
 }
}

export const CLOUD_RUN_SERVICE_NAMES=['sentinelops-frontend','sentinelops-api-gateway','sentinelops-orchestrator','sentinelops-forecast-service','sentinelops-simulation-service','sentinelops-verification-service','sentinelops-evidence-service','sentinelops-gemma-service','sentinelops-mcp-server'] as const;

export function normalizeArchitectureStatus(row?:IntegrationHealth):ArchitectureStatus{
 const value=(row?.status??'').toUpperCase();
 if(value.includes('BLOCKED')||value.includes('ACCESS'))return'BLOCKED_BY_PARTICIPANT_ACCESS';
 if(value.includes('FAIL'))return'FAILED';
 if(value==='IMPLEMENTED_AND_VERIFIED')return row?.last_successful_call?'VERIFIED_LIVE':'VERIFIED_LOCAL';
 if(value.includes('REQUIRES_CREDENTIALS'))return'IMPLEMENTED_REQUIRES_CREDENTIALS';
 if(value.includes('LOCAL_ADAPTER'))return'LOCAL_ADAPTER_ONLY';
 if(value.includes('FALLBACK'))return'FALLBACK_ACTIVE';
 return'NOT_YET_EXECUTED';
}

export function componentStatus(component:ArchitectureComponent,rows?:IntegrationHealth[],antigravityStatus?:string):ArchitectureStatus{
 if(component.domain==='Participant Boundary')return antigravityStatus?.includes('BLOCKED')?'BLOCKED_BY_PARTICIPANT_ACCESS':component.defaultStatus;
 if(!component.integrationKey)return component.defaultStatus;
 const key=component.integrationKey.toLowerCase();const row=rows?.find(item=>item.integration.toLowerCase()===key||item.integration.toLowerCase().includes(key));
 return row?normalizeArchitectureStatus(row):component.defaultStatus==='VERIFIED_LOCAL'?'NOT_YET_EXECUTED':component.defaultStatus;
}

export function cloudRunServices(rows?:IntegrationHealth[]):CloudRunServiceView[]{
 const row=rows?.find(item=>item.integration.toLowerCase()==='cloud run');const status=componentStatus({...ARCHITECTURE_COMPONENTS[0],integrationKey:'Cloud Run'},rows);
 return CLOUD_RUN_SERVICE_NAMES.map(service=>({service,region:'asia-south1',revision:'NOT_YET_EXECUTED',url:'NOT_YET_EXECUTED',health:row?.last_successful_call?'EVIDENCE_AVAILABLE':'NOT_YET_EXECUTED',readiness:row?.last_successful_call?'EVIDENCE_AVAILABLE':'NOT_YET_EXECUTED',authenticationMode:service==='sentinelops-frontend'?'Public product surface':'Authenticated private-service boundary',serviceAccount:'NOT_YET_EXECUTED',status}));
}

export const CANONICAL_WORKFLOW=['Telemetry Ingestion','Redis Forecast Service','Digital Twin Engine','Simulation Engine','Optimization Engine','Gemini Reasoning','Gemma Policy Review','Mandatory Safety Gates','Verification Agent','Executive Recommendation','AWAITING_HUMAN','Human Approval','Tamper-Evident SHA-256-Linked Audit Chain','Evidence ZIP Export'];
export const BIGQUERY_FLOWS=['Historical telemetry','Forecast results','Simulation results','Verification results','Model invocation metadata','Audit exports','Evidence metadata','Business-impact estimates','Analytics'];
export const PUBSUB_EVENTS=['Telemetry Event','Agent Task Event','Simulation Event','Verification Event','Model Invocation Event','Evidence Export Event','Workflow Status Event','BigQuery Export Event'];
