import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Activity,ArrowLeft,RefreshCw,ShieldCheck} from 'lucide-react';
import {nexusApi} from '../api/client';
import type {NexusAgent} from '../types';

export default function AgentPage(){const parts=location.pathname.split('/').filter(Boolean);const name=parts[1];const qc=useQueryClient();const workflows=useQuery({queryKey:['workflows'],queryFn:nexusApi.workflows});const run=workflows.data?.[0];const agents=useQuery({queryKey:['agents',run?.id],queryFn:()=>nexusApi.agents(run!.id),enabled:!!run});const selected=name?agents.data?.find(x=>x.agent_name===name):undefined;const action=useMutation({mutationFn:(rerun:boolean)=>nexusApi.runAgent(run!.id,name,rerun),onSuccess:()=>qc.invalidateQueries({queryKey:['agents',run?.id]})});if(!run||agents.isLoading)return <Shell><p>Loading workforce…</p></Shell>;if(!name)return <Shell><h1>AI Workforce</h1><p>Every agent opens a backend-connected workspace.</p><div className="workforce-grid">{agents.data?.map(agent=><a href={`/agents/${agent.agent_name}`} key={agent.agent_name}><Activity/><b>{agent.display_name}</b><span>{agent.purpose}</span><em>{agent.current_status}</em></a>)}</div></Shell>;if(!selected)return <Shell><h1>Agent not found</h1></Shell>;return <Shell><a href="/agents"><ArrowLeft/> All agents</a><header className="workspace-head"><div><small>AGENT WORKSPACE · WORKFLOW {run.id}</small><h1>{selected.display_name}</h1><p>{selected.purpose}</p></div><strong>{selected.current_status}</strong></header><div className="workspace-actions"><button onClick={()=>action.mutate(false)} disabled={action.isPending}>Run Agent</button><button onClick={()=>action.mutate(true)} disabled={action.isPending}><RefreshCw/> Re-run Agent</button><a href={`/workflows/${run.id}/audit`}>View Audit Events</a><a href={`/workflows/${run.id}/evidence`}>View Evidence</a></div>{action.isError&&<p className="form-error">{action.error.message}</p>}<div className="workspace-grid"><Card title="Responsibilities" value={selected.responsibilities}/><Card title="Structured reasoning summary" value={selected.reasoning_summary}/><Card title="Inputs" value={selected.input_artifact}/><Card title="Outputs" value={selected.output_artifact}/><Card title="Evidence references" value={selected.evidence_references}/><Card title="Assumptions" value={selected.assumptions}/><Card title="Execution" value={{last_execution_time:selected.last_execution_time,duration_ms:selected.execution_duration_ms,retry_count:selected.retry_count,result_hash:selected.result_hash}}/><Card title="Errors" value={selected.errors||'None'}/></div></Shell>}
function Card({title,value}:{title:string;value:unknown}){return <article className="workspace-card"><h2>{title}</h2><pre>{typeof value==='string'?value:JSON.stringify(value,null,2)}</pre></article>}
function Shell({children}:{children:React.ReactNode}){return <div className="product-page"><nav><a href="/"><b>SENTINELOPS NEXUS</b></a><a href="/command-centre">Command Centre</a></nav><main>{children}<div className="boundary"><ShieldCheck/> PRODUCTION ACTION: NOT EXECUTED</div></main></div>}

