import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {afterEach,describe,expect,it,vi} from 'vitest';
import ArchitecturePage from './ArchitecturePage';
import {ARCHITECTURE_COMPONENTS,ARCHITECTURE_DOMAINS,BIGQUERY_FLOWS,CANONICAL_WORKFLOW,CLOUD_RUN_SERVICE_NAMES,PUBSUB_EVENTS} from '../features/architecture/architectureData';

const integrations=[
 {integration:'Gemini',status:'LOCAL_FALLBACK_AVAILABLE',last_health_check:'2026-08-07',configured_service:'gemini-2.5-flash',fallback_status:'ACTIVE',trace_id:'trace-fallback',documentation:'/docs#gemini',production_action:'NOT_EXECUTED'},
 {integration:'Gemma',status:'LOCAL_ADAPTER_ONLY',last_health_check:'2026-08-07',configured_service:'local-policy-adapter',fallback_status:'ACTIVE',documentation:'/docs#gemma',production_action:'NOT_EXECUTED'},
 {integration:'ADK',status:'LOCAL_ADAPTER_ONLY',last_health_check:'2026-08-07',configured_service:'adk',fallback_status:'NOT_INVOKED',documentation:'/docs#adk',production_action:'NOT_EXECUTED'},
 {integration:'A2A',status:'IMPLEMENTED_AND_VERIFIED',last_health_check:'2026-08-07',configured_service:'a2a',fallback_status:'NOT_INVOKED',documentation:'/docs#a2a',production_action:'NOT_EXECUTED'},
 {integration:'MCP',status:'IMPLEMENTED_AND_VERIFIED',last_health_check:'2026-08-07',configured_service:'mcp',fallback_status:'NOT_INVOKED',documentation:'/docs#mcp',production_action:'NOT_EXECUTED'},
 {integration:'BigQuery',status:'IMPLEMENTED_REQUIRES_CREDENTIALS',last_health_check:'2026-08-07',configured_service:'sentinelops_nexus',fallback_status:'NOT_INVOKED',documentation:'/docs#bigquery',production_action:'NOT_EXECUTED'},
 {integration:'Pub/Sub',status:'IMPLEMENTED_REQUIRES_CREDENTIALS',last_health_check:'2026-08-07',configured_service:'sentinelops-workflow-events',fallback_status:'NOT_INVOKED',documentation:'/docs#pubsub',production_action:'NOT_EXECUTED'},
 {integration:'Cloud Run',status:'IMPLEMENTED_REQUIRES_CREDENTIALS',last_health_check:'2026-08-07',configured_service:'cloud-run',fallback_status:'NOT_INVOKED',documentation:'/docs#cloud-run',production_action:'NOT_EXECUTED'},
 {integration:'OpenTelemetry',status:'LOCAL_ADAPTER_ONLY',last_health_check:'2026-08-07',configured_service:'opentelemetry',fallback_status:'NOT_INVOKED',documentation:'/docs#otel',production_action:'NOT_EXECUTED'},
 {integration:'OAuth2/JWT',status:'LOCAL_ADAPTER_ONLY',last_health_check:'2026-08-07',configured_service:'oauth2/jwt',fallback_status:'NOT_INVOKED',documentation:'/docs#oauth',production_action:'NOT_EXECUTED'}
];
const mockFetch=()=>vi.fn(async(input:RequestInfo|URL)=>({ok:true,json:async()=>String(input).includes('antigravity')?{status:'BLOCKED_BY_PARTICIPANT_ACCESS',official_runtime_invoked:false,blocker:'Participant access unavailable',production_action:'NOT_EXECUTED'}:integrations}) as Response);
const renderPage=()=>render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><ArchitecturePage/></QueryClientProvider>);
afterEach(()=>{cleanup();vi.restoreAllMocks();history.replaceState({},'','/')});

describe('interactive enterprise architecture explorer',()=>{
 it('renders every required domain and removes the obsolete JSON-only architecture',async()=>{history.replaceState({},'','/architecture');vi.stubGlobal('fetch',mockFetch());renderPage();await screen.findByText('Explore every authority, evidence, and runtime boundary.');for(const domain of ARCHITECTURE_DOMAINS)expect(screen.getAllByText(domain).length).toBeGreaterThan(0);expect(document.querySelector('pre')).toBeNull();expect(screen.queryByText(/No cloud or production execution adapter exists/)).toBeNull()});
 it('renders every typed component as a clickable semantic button',async()=>{history.replaceState({},'','/architecture');vi.stubGlobal('fetch',mockFetch());renderPage();await screen.findByText('Explore every authority, evidence, and runtime boundary.');const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>('.architecture-node'));expect(buttons).toHaveLength(ARCHITECTURE_COMPONENTS.length);for(const button of buttons){fireEvent.click(button);expect(button.getAttribute('aria-pressed')).toBe('true');expect(location.search).toContain(`component=${button.id.replace('architecture-component-','')}`)}});
 it('updates the explanation panel, URL, keyboard selection, and purpose-first order',async()=>{history.replaceState({},'','/architecture');vi.stubGlobal('fetch',mockFetch());renderPage();await screen.findByText('Explore every authority, evidence, and runtime boundary.');const gemini=screen.getByRole('button',{name:/Gemini Enterprise Agent Platform/});fireEvent.click(gemini);const panel=document.getElementById('architecture-component-panel')!;expect(within(panel).getByRole('heading',{name:'Gemini Enterprise Agent Platform'})).toBeTruthy();expect(location.search).toContain('component=gemini-enterprise-agent-platform');const content=panel.textContent??'';expect(content.indexOf('1. Component purpose')).toBeLessThan(content.indexOf('4. What is implemented'));expect(content.indexOf('5. What is missing')).toBeLessThan(content.indexOf('9. Current status'));fireEvent.keyDown(gemini,{key:'ArrowRight'});expect(location.search).toContain('component=gemma-private-policy-review-engine')});
 it('supports direct links and popstate browser navigation',async()=>{history.replaceState({},'','/architecture?component=bigquery');vi.stubGlobal('fetch',mockFetch());renderPage();let panel=document.getElementById('architecture-component-panel')!;expect(within(panel).getByRole('heading',{name:'BigQuery'})).toBeTruthy();history.pushState({},'','/architecture?component=pub-sub');dispatchEvent(new PopStateEvent('popstate'));await waitFor(()=>{panel=document.getElementById('architecture-component-panel')!;expect(within(panel).getByRole('heading',{name:'Pub/Sub'})).toBeTruthy()})});
 it('renders the exact canonical order, legend, BigQuery flows, and Pub/Sub events',async()=>{history.replaceState({},'','/architecture');vi.stubGlobal('fetch',mockFetch());renderPage();await screen.findByText('Safety order is an invariant');const flow=document.querySelector('.canonical-flow')!.textContent??'';for(let i=1;i<CANONICAL_WORKFLOW.length;i++)expect(flow.indexOf(CANONICAL_WORKFLOW[i-1])).toBeLessThan(flow.indexOf(CANONICAL_WORKFLOW[i]));expect(screen.getByLabelText('Data flow legend')).toBeTruthy();for(const label of BIGQUERY_FLOWS)expect(screen.getByText(label)).toBeTruthy();for(const event of PUBSUB_EVENTS)expect(screen.getByText(event)).toBeTruthy()});
 it('renders all nine Cloud Run services without hardcoded live success',async()=>{history.replaceState({},'','/architecture');vi.stubGlobal('fetch',mockFetch());renderPage();await screen.findByText('Cloud Run service inventory');for(const service of CLOUD_RUN_SERVICE_NAMES)expect(screen.getByRole('heading',{name:service})).toBeTruthy();expect(screen.getAllByText('NOT_YET_EXECUTED').length).toBeGreaterThan(0);expect(screen.queryByText('VERIFIED_LIVE')).toBeNull()});
 it('renders authority prohibitions and never exposes a production action control',async()=>{history.replaceState({},'','/architecture');vi.stubGlobal('fetch',mockFetch());renderPage();await screen.findByText('Explanation is separated from decision authority');expect(screen.getByText(/Approve; override gates; mutate state/)).toBeTruthy();expect(screen.getByText(/Deploy; scale; roll back; shell; modify infrastructure/)).toBeTruthy();expect(screen.getAllByText('PRODUCTION ACTION: NOT EXECUTED').length).toBeGreaterThan(0);expect(screen.queryByRole('button',{name:/deploy|scale|roll back|reconfigure|execute production/i})).toBeNull()});
 it('uses reduced-motion scrolling and exposes responsive map structure',async()=>{history.replaceState({},'','/architecture');const scroll=vi.fn();Object.defineProperty(HTMLElement.prototype,'scrollIntoView',{configurable:true,value:scroll});vi.stubGlobal('matchMedia',vi.fn(()=>({matches:true,media:'(prefers-reduced-motion: reduce)',addEventListener:vi.fn(),removeEventListener:vi.fn()})));vi.stubGlobal('fetch',mockFetch());renderPage();await screen.findByText('Explore every authority, evidence, and runtime boundary.');fireEvent.click(screen.getByRole('button',{name:/Command Centre/}));expect(scroll).toHaveBeenCalledWith(expect.objectContaining({behavior:'auto'}));expect(document.querySelector('.architecture-map-shell')).toBeTruthy();expect(document.querySelector('.architecture-panel')).toBeTruthy()});
});
