import {useEffect,useMemo,useRef,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {ArrowLeft,ArrowRight,Box,CheckCircle2,ChevronRight,Cloud,Eye,Filter,GitBranch,LockKeyhole,Minus,Plus,RotateCcw,ShieldCheck,UserRound,Waypoints} from 'lucide-react';
import {nexusApi} from '../api/client';
import {ARCHITECTURE_COMPONENTS,ARCHITECTURE_DOMAINS,BIGQUERY_FLOWS,CANONICAL_WORKFLOW,PUBSUB_EVENTS,cloudRunServices,componentStatus} from '../features/architecture/architectureData';
import type {ArchitectureComponent,ArchitectureDomain,ArchitectureStatus,IntegrationHealth} from '../features/architecture/types';
import '../features/architecture/architecture.css';
import Navbar from '../components/Navbar';

const boundaryText='Google Cloud deployment and managed-service integrations are implemented where verified. No endpoint, model, agent, or tool is permitted to deploy, scale, roll back, reconfigure, or modify production infrastructure.';
const initialComponent=()=>new URLSearchParams(location.search).get('component')??ARCHITECTURE_COMPONENTS[0].id;
const statusClass=(status:ArchitectureStatus)=>status.toLowerCase().replaceAll('_','-');

export default function ArchitecturePage(){
 const integrations=useQuery({queryKey:['architecture-integrations'],queryFn:nexusApi.integrations,staleTime:30_000,retry:1});
 const antigravity=useQuery({queryKey:['architecture-antigravity'],queryFn:nexusApi.antigravity,staleTime:60_000,retry:1});
 const [selectedId,setSelectedId]=useState(initialComponent);const [domain,setDomain]=useState<'ALL'|ArchitectureDomain>('ALL');const [onlyLive,setOnlyLive]=useState(false);const [showBoundaries,setShowBoundaries]=useState(true);const [zoom,setZoom]=useState(1);
 const panelRef=useRef<HTMLElement>(null);
 const statuses=useMemo(()=>new Map(ARCHITECTURE_COMPONENTS.map(component=>[component.id,componentStatus(component,integrations.data as IntegrationHealth[]|undefined,antigravity.data?.status)])),[integrations.data,antigravity.data?.status]);
 const visible=useMemo(()=>ARCHITECTURE_COMPONENTS.filter(component=>(domain==='ALL'||component.domain===domain)&&(!onlyLive||statuses.get(component.id)==='VERIFIED_LIVE')),[domain,onlyLive,statuses]);
 const selected=ARCHITECTURE_COMPONENTS.find(component=>component.id===selectedId)??visible[0]??ARCHITECTURE_COMPONENTS[0];
 const select=(id:string,push=true)=>{setSelectedId(id);if(push){const url=new URL(location.href);url.searchParams.set('component',id);history.pushState({},'',`${url.pathname}${url.search}`)}const reduced=typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;const panel=panelRef.current;if(typeof panel?.scrollIntoView==='function')panel.scrollIntoView({behavior:reduced?'auto':'smooth',block:'nearest'})};
 const index=Math.max(0,visible.findIndex(component=>component.id===selected.id));
 const reset=()=>{setDomain('ALL');setOnlyLive(false);setShowBoundaries(true);setZoom(1);select(ARCHITECTURE_COMPONENTS[0].id)};
 useEffect(()=>{const pop=()=>setSelectedId(initialComponent());addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[]);
 const rows=integrations.data as IntegrationHealth[]|undefined;const services=cloudRunServices(rows);
 return <div className="product-page architecture-page"><Navbar/><div className="architecture-safety"><ShieldCheck/> PRODUCTION ACTION: NOT EXECUTED</div><main>
  <header className="architecture-hero"><div><small>GOOGLE-NATIVE ENTERPRISE ARCHITECTURE</small><h1>Explore every authority, evidence, and runtime boundary.</h1><p>{boundaryText}</p></div><div><Cloud/><b>{ARCHITECTURE_COMPONENTS.length} clickable components</b><span>{ARCHITECTURE_DOMAINS.length} architecture domains</span></div></header>
  {(integrations.isError||antigravity.isError)&&<div className="architecture-warning" role="alert">Managed integration status is unavailable. Components remain explorable and display their bounded local or not-yet-executed state.</div>}
  <section className="canonical-flow" aria-labelledby="canonical-title"><header><Waypoints/><div><small>CANONICAL DECISION WORKFLOW</small><h2 id="canonical-title">Safety order is an invariant</h2></div></header><div>{CANONICAL_WORKFLOW.map((step,i)=><span key={step} className={step==='Mandatory Safety Gates'||step==='Verification Agent'?'authority-step':step==='Human Approval'?'human-step':''}><b>{step}</b>{i<CANONICAL_WORKFLOW.length-1&&<ChevronRight/>}</span>)}</div></section>
  <section className="architecture-toolbar" aria-label="Architecture controls"><label><Filter/> Domain<select aria-label="Filter by architecture domain" value={domain} onChange={event=>setDomain(event.target.value as 'ALL'|ArchitectureDomain)}><option value="ALL">All domains</option>{ARCHITECTURE_DOMAINS.map(item=><option key={item}>{item}</option>)}</select></label><label className="check"><input type="checkbox" checked={onlyLive} onChange={event=>setOnlyLive(event.target.checked)}/> Show only verified live components</label><label className="check"><input type="checkbox" checked={showBoundaries} onChange={event=>setShowBoundaries(event.target.checked)}/> Show all boundaries</label><div><button aria-label="Zoom out" onClick={()=>setZoom(value=>Math.max(.75,value-.1))}><Minus/></button><button aria-label="Zoom in" onClick={()=>setZoom(value=>Math.min(1.25,value+.1))}><Plus/></button><button onClick={()=>setZoom(1)}><Eye/> Fit to screen</button><button onClick={reset}><RotateCcw/> Reset view</button></div></section>
  <section className="architecture-layout"><div className="architecture-map-shell"><aside className="architecture-legend" aria-label="Data flow legend"><b>LEGEND</b><span><i className="solid"/> synchronous request</span><span><i className="dashed"/> asynchronous Pub/Sub event</span><span><i className="dotted"/> telemetry or trace flow</span><span><i className="double"/> evidence export</span><span><ShieldCheck/> deterministic authority</span><span><UserRound/> mandatory human decision</span><span><LockKeyhole/> authenticated private service</span></aside><div className="architecture-map" style={{'--architecture-zoom':zoom} as React.CSSProperties}>
   {ARCHITECTURE_DOMAINS.map(item=>{const components=visible.filter(component=>component.domain===item);if(!components.length)return null;return <section className="architecture-domain" key={item}><header><span>{item}</span><small>{components.length} components</small></header><div>{components.map((component,componentIndex)=><ArchitectureButton key={component.id} component={component} status={statuses.get(component.id)??'NOT_YET_EXECUTED'} selected={component.id===selected.id} showBoundary={showBoundaries} onSelect={select} onKey={(direction)=>{const next=Math.max(0,Math.min(visible.length-1,visible.indexOf(component)+direction));select(visible[next].id);document.getElementById(`architecture-component-${visible[next].id}`)?.focus()}} index={componentIndex}/>)}</div></section>})}
   {!visible.length&&<div className="architecture-empty">No components have backend-confirmed <b>VERIFIED_LIVE</b> evidence in the current response. Clear the filter to inspect implemented and bounded components.</div>}
  </div></div><ArchitecturePanel panelRef={panelRef} component={selected} status={statuses.get(selected.id)??'NOT_YET_EXECUTED'} integration={selected.integrationKey?rows?.find(row=>row.integration.toLowerCase().includes(selected.integrationKey!.toLowerCase())):undefined}/></section>
  <section className="architecture-controls-row"><button disabled={index===0} onClick={()=>select(visible[index-1]?.id)}><ArrowLeft/> Previous component</button><span>{index+1} / {visible.length}</span><button disabled={index>=visible.length-1} onClick={()=>select(visible[index+1]?.id)}>Next component <ArrowRight/></button></section>
  <PlatformLifecycles/><DataArchitecture/><CloudRunInventory services={services}/><AuthorityMatrix/>
  <div className="boundary"><ShieldCheck/> PRODUCTION ACTION: NOT EXECUTED</div>
 </main></div>;
}

function ArchitectureButton({component,status,selected,showBoundary,onSelect,onKey,index}:{component:ArchitectureComponent;status:ArchitectureStatus;selected:boolean;showBoundary:boolean;onSelect:(id:string)=>void;onKey:(direction:number)=>void;index:number}){return <button id={`architecture-component-${component.id}`} type="button" className={`architecture-node ${selected?'selected':''} ${showBoundary&&component.boundary?`boundary-${component.boundary}`:''}`} aria-pressed={selected} aria-controls="architecture-component-panel" onClick={()=>onSelect(component.id)} onKeyDown={event=>{if(event.key==='ArrowRight'||event.key==='ArrowDown'){event.preventDefault();onKey(1)}else if(event.key==='ArrowLeft'||event.key==='ArrowUp'){event.preventDefault();onKey(-1)}}}><span>{String(index+1).padStart(2,'0')}</span><b>{component.title}</b><small className={statusClass(status)}>{status}</small>{component.boundary==='deterministic'?<ShieldCheck/>:component.boundary==='human'?<UserRound/>:component.boundary==='authenticated'?<LockKeyhole/>:<Box/>}</button>}

const Items=({title,items}:{title:string;items:string[]})=><section><h3>{title}</h3>{items.length?<ul>{items.map(item=><li key={item}>{item}</li>)}</ul>:<p>NOT_YET_EXECUTED</p>}</section>;
function ArchitecturePanel({component,status,integration,panelRef}:{component:ArchitectureComponent;status:ArchitectureStatus;integration?:IntegrationHealth;panelRef:React.RefObject<HTMLElement>}){return <article ref={panelRef} id="architecture-component-panel" className="architecture-panel" aria-live="polite" tabIndex={-1}><header><div><small>{component.domain}</small><h2>{component.title}</h2></div><Status status={status}/></header><section className="panel-purpose"><Waypoints/><div><h3>1. Component purpose</h3><p>{component.purpose}</p></div></section><section><h3>2. What it does</h3><p>{component.whatItDoes}</p></section><section><h3>3. Why it matters</h3><p>{component.whyItMatters}</p></section><Items title="4. What is implemented" items={component.implemented}/><Items title="5. What is missing" items={component.missingEvidence}/><section><h3>6. Inputs</h3><p>{component.inputs.join(' · ')}</p></section><section><h3>7. Outputs</h3><p>{component.outputs.join(' · ')}</p></section><section className="panel-authority"><h3>8. Authority boundary</h3><p>{component.authority}</p></section><section><h3>9. Current status</h3><Status status={status}/>{integration&&<dl><dt>Configured service</dt><dd>{integration.configured_service}</dd><dt>Last successful call</dt><dd>{integration.last_successful_call??'NOT_YET_EXECUTED'}</dd><dt>Trace ID</dt><dd>{integration.trace_id??'NOT_YET_EXECUTED'}</dd></dl>}</section><Items title="10. Evidence available" items={component.evidence}/><Items title="11. Google Cloud service" items={component.googleCloudServices}/><Items title="12. Security controls" items={component.security}/><section><h3>13. Failure and fallback behavior</h3><p>{component.failureBehavior}</p><p><b>Fallback:</b> {component.fallback}</p></section><Items title="14. Related components" items={component.related}/><section className="panel-takeaway"><h3>Judge takeaway</h3><p>{component.judgeTakeaway}</p></section><footer><ShieldCheck/> PRODUCTION ACTION: NOT EXECUTED</footer></article>}

function Status({status}:{status:ArchitectureStatus}){return <span className={`architecture-status ${statusClass(status)}`}><CheckCircle2/>{status}</span>}

function PlatformLifecycles(){const ai=['Google AI Studio','Prompt Management','Prompt Evaluation','Gemini Runtime','Gemma Policy Review'];const deploy=['GitHub','GitHub Actions','Cloud Build','Artifact Registry','Cloud Run'];const runtime=['BigQuery','Pub/Sub','Secret Manager','IAM / Service Accounts','Cloud Logging','Cloud Monitoring','Cloud Trace'];return <section className="platform-lifecycles"><header><Cloud/><div><small>GOOGLE-NATIVE LIFECYCLES</small><h2>AI engineering, delivery, and runtime services</h2></div></header><div className="lifecycle-grid"><article><h3>AI lifecycle</h3><div className="lifecycle-flow">{ai.map((item,index)=><span key={item}><b>{item}</b>{index<ai.length-1&&<ChevronRight/>}</span>)}</div></article><article><h3>Deployment lifecycle</h3><div className="lifecycle-flow">{deploy.map((item,index)=><span key={item}><b>{item}</b>{index<deploy.length-1&&<ChevronRight/>}</span>)}</div></article></div><div className="runtime-services"><b>Connected runtime services</b>{runtime.map(item=><span key={item}>{item}</span>)}</div></section>}

function DataArchitecture(){return <section className="data-architecture"><header><GitBranch/><div><small>ANALYTICS AND ASYNCHRONOUS EVENTS</small><h2>Evidence flows without surrendering workflow authority</h2></div></header><div className="data-columns"><article><h3>BigQuery analytical flows</h3><p>BigQuery is the analytical and historical evidence warehouse. Backend transactional state remains authoritative.</p><div className="flow-tags">{BIGQUERY_FLOWS.map(item=><span key={item}>{item}<ChevronRight/><b>BigQuery</b></span>)}</div></article><article><h3>Pub/Sub event backbone</h3><p>Every envelope carries schema version, idempotency, retry, dead-letter, correlation, causation, and trace metadata.</p><div className="event-tags">{PUBSUB_EVENTS.map(item=><span key={item}>{item}</span>)}</div></article></div></section>}

function CloudRunInventory({services}:{services:ReturnType<typeof cloudRunServices>}){return <section className="cloud-inventory"><header><Cloud/><div><small>NINE INDEPENDENTLY PACKAGEABLE SERVICES</small><h2>Cloud Run service inventory</h2><p>Values are backend-derived where available; missing revision, URL, health, readiness, identity, or smoke evidence remains NOT_YET_EXECUTED.</p></div></header><div>{services.map(service=><article key={service.service}><h3>{service.service}</h3><Status status={service.status}/><dl><dt>Region</dt><dd>{service.region}</dd><dt>Revision</dt><dd>{service.revision}</dd><dt>URL</dt><dd>{service.url}</dd><dt>Health</dt><dd>{service.health}</dd><dt>Readiness</dt><dd>{service.readiness}</dd><dt>Authentication</dt><dd>{service.authenticationMode}</dd><dt>Service account</dt><dd>{service.serviceAccount}</dd></dl></article>)}</div></section>}

function AuthorityMatrix(){const rows=[['Gemini','Explain; detect contradictions','Approve; override gates; mutate state; execute production'],['Gemma','Critique policy consistency','Approve; override gates; change eligibility'],['Google ADK','Orchestrate bounded agents','Own final workflow state'],['A2A','Carry typed messages','Bypass backend policy'],['MCP','Call controlled tools','Deploy; scale; roll back; shell; modify infrastructure'],['Human','Senior Developer may decide with verified role and rationale','Intern approval'],['Backend','Workflow transitions; gates; authorization; audit; export','Production infrastructure execution']];return <section className="authority-matrix"><header><ShieldCheck/><div><small>AUTHORITY MATRIX</small><h2>Explanation is separated from decision authority</h2></div></header><div className="authority-table"><b>Actor</b><b>Permitted</b><b>Prohibited</b>{rows.flatMap(row=>row.map((cell,index)=><span className={index===2?'prohibited':''} key={`${row[0]}-${index}`}>{cell}</span>))}</div></section>}
