import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {afterEach,describe,expect,it,vi} from 'vitest';
import App from './App';

class ResizeObserverMock{observe(){}unobserve(){}disconnect(){}}
vi.stubGlobal('ResizeObserver',ResizeObserverMock);
Element.prototype.scrollIntoView=vi.fn();

const gate=(name:string,passed=true)=>({gate:name,mandatory:true,passed,details:passed?'passed':'failed',evidence_ids:['ev-config']});
const run={id:1,name:'Payment capacity forecast',state:'RECOMMENDED',seed:20260808,inputs_json:{traffic_multiplier:1,redis_capacity:12000,application_replicas:4,dependency_latency_ms:20,failover_state:'primary',business:{}},forecast_json:{predicted_crossing_minutes:30,predicted_customer_impact_minutes:45,confidence_label:'High',heuristic_evidence_score:85,equation:'memory_pct(t) = 72 + 0.6 * minutes',safe_threshold_pct:90,residual_mae:0,error_bound_minutes:3,assumptions:['Capacity remains fixed']},twin_json:{twin_id:'twin-1',random_seed:20260808,network_policy:'disabled',manifest_hash:'1234567890123456',source_revision:'abcdef1234'},scenarios_json:[{scenario_id:'redis-crash',name:'Redis Crash',inputs:{},status:'fail',bottleneck_avoided:false,p95_ms:5000,error_rate_pct:100,recovery_minutes:18,result_hash:'1234567890abcdef',evidence_ids:['ev-config']}],tournament_json:{recommended_candidate_id:'optimal',weights:{safety:.2},rule:'Eligibility overrides score',twin_id:'twin-1',candidates:[{candidate_id:'fast',name:'FAST',action:'Scale applications',expected_benefit:'capacity',cost_estimate_inr:42000,risk_score:32,recovery_minutes:4,reversible:false,assumptions:[],gates:[gate('failover_test',false)],score_components:{},score:72,eligible:false,verdict:'Disqualified'},{candidate_id:'optimal',name:'OPTIMAL',action:'Correct cache policy',expected_benefit:'capacity',cost_estimate_inr:154000,risk_score:9,recovery_minutes:6,reversible:true,assumptions:[],gates:[gate('failover_test')],score_components:{},score:91,eligible:true,verdict:'Eligible'}]},impact_json:{revenue_exposure_inr:27000000,customers_at_risk:22000,sla_breach_risk_label:'High',formula:'request rate x risk window',inputs:{conversion_rate:.034},disclaimer:'Operational estimate'},recommendation_json:{summary:'Redis capacity risk',recommendation:'Recommend OPTIMAL',contradictory_evidence:['Current errors remain low']},human_decision_json:{},production_action_executed:false,created_at:'2026-08-03',updated_at:'2026-08-03'};
const telemetry=[{label:'Now',minute:0,request_rate:8500,p50_ms:60,p95_ms:140,p99_ms:200,redis_cpu_pct:63,redis_memory_pct:72,cache_hit_rate_pct:78,queue_depth:3,application_replicas:4,error_rate_pct:0,order_conversion_rate:.034,average_order_value_inr:3200,reactive_alert:false}];

function mockApi(currentRun=run){vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input);let data:unknown=[];if(url.endsWith('/api/v1/demo/bootstrap'))data=currentRun;else if(url.endsWith('/api/v1/workflows'))data=[currentRun];else if(url.includes('/telemetry'))data=telemetry;else if(url.includes('/evidence'))data=[{id:1,evidence_id:'ev-config',category:'configuration',source:'seeded',observed_at:'2026-08-03',payload_json:{},summary:'Capacity captured',content_hash:'1234567890abcdef'}];else if(url.includes('/timeline'))data=[{id:1,sequence:1,event_type:'run.created',actor:'orchestrator',payload_json:{},previous_hash:'0',event_hash:'1234567890abcdef',created_at:'2026-08-03'}];else if(url.includes('/agents'))data=[{agent_name:'observer-agent',display_name:'Observer Agent',purpose:'Observe',responsibilities:[],current_status:'OBSERVED',workflow_id:1,input_artifact:{},output_artifact:{},evidence_references:['ev-config'],assumptions:[],retry_count:0,supported_actions:['run'],reasoning_summary:'Structured summary'}];else if(url.includes('/approve')&&init?.method==='POST')data={production_action:'NOT EXECUTED'};return {ok:true,json:async()=>data} as Response}))}

afterEach(()=>{cleanup();vi.restoreAllMocks()});
describe('SentinelOps Nexus',()=>{
 it('renders real workflow data and the safety boundary',async()=>{mockApi();render(<QueryClientProvider client={new QueryClient()}><App/></QueryClientProvider>);expect(await screen.findByText("Predict tomorrow's bottleneck before customers experience it.")).toBeTruthy();expect(screen.getAllByText('NOT EXECUTED').length).toBeGreaterThan(0);expect(screen.getByText('Intervention Tournament')).toBeTruthy();expect(screen.getByText('DISQUALIFIED')).toBeTruthy()});
 it('starts the guided demo in one click without approving',async()=>{mockApi();render(<QueryClientProvider client={new QueryClient()}><App/></QueryClientProvider>);fireEvent.click(await screen.findByRole('button',{name:'One-click Guided Demo'}));expect(screen.getByRole('dialog',{name:'Guided Demo'})).toBeTruthy();expect(screen.getByText('Tomorrow, before the alert')).toBeTruthy();expect(screen.getAllByText('PRODUCTION ACTION: NOT EXECUTED').length).toBeGreaterThan(0);expect(fetch).not.toHaveBeenCalledWith(expect.stringContaining('/approve'),expect.anything())});
 it('offers interactive exploration presets and scenario inspection',async()=>{mockApi();render(<QueryClientProvider client={new QueryClient()}><App/></QueryClientProvider>);fireEvent.click(await screen.findByRole('button',{name:'Explore Mode'}));expect(screen.getByRole('button',{name:'10x traffic'})).toBeTruthy();expect(screen.getByText('SELECTED SCENARIO')).toBeTruthy();expect(screen.getByText('Bottleneck avoided')).toBeTruthy()});
 it('offers a manual operational evidence upload',async()=>{mockApi();render(<QueryClientProvider client={new QueryClient()}><App/></QueryClientProvider>);expect(await screen.findByLabelText('Upload operational JSON')).toBeTruthy()});
 it('runs uploaded operational JSON through the backend and shows the selected filename',async()=>{const imported={...run,id:9,inputs_json:{...run.inputs_json,traffic_multiplier:3,redis_capacity:9000,application_replicas:3,dependency_latency_ms:160},scenarios_json:[...run.scenarios_json,...Array.from({length:11},(_,index)=>({...run.scenarios_json[0],scenario_id:`scenario-${index}`,name:`Scenario ${index}`}))]};const fetchMock=vi.fn(async(input:RequestInfo|URL)=>{const url=String(input);let data:unknown=[];if(url.endsWith('/api/v1/demo/bootstrap'))data=run;else if(url.endsWith('/api/v1/workflows/import-json'))data=imported;else if(url.includes('/telemetry'))data=telemetry;else if(url.includes('/evidence')||url.includes('/timeline')||url.includes('/agents'))data=[];return {ok:true,json:async()=>data} as Response});vi.stubGlobal('fetch',fetchMock);render(<QueryClientProvider client={new QueryClient()}><App/></QueryClientProvider>);const input=await screen.findByLabelText('Upload operational JSON');fireEvent.change(input,{target:{files:[new File(['{"controls":{"traffic_multiplier":3}}'],'organization.json',{type:'application/json'})]}});expect(await screen.findByText('organization.json')).toBeTruthy();expect(await screen.findByText(/Uploaded organization.json successfully.*12 calculated scenarios/)).toBeTruthy();expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/api/v1/workflows/import-json'),expect.objectContaining({method:'POST'}))});
 it('routes approval through authorized human verification without submitting automatically',async()=>{mockApi();render(<QueryClientProvider client={new QueryClient()}><App/></QueryClientProvider>);const link=await screen.findByRole('link',{name:'Verify role and review proposal'});expect(link.getAttribute('href')).toBe('/workflows/1/approval');expect(fetch).not.toHaveBeenCalledWith(expect.stringContaining('/approve'),expect.anything())})
 it('explains a recorded decision and revoked export',async()=>{mockApi({...run,state:'DECIDED',human_decision_json:{exported_at:'2026-08-03T12:00:00Z',export_status:'consumed'}});render(<QueryClientProvider client={new QueryClient()}><App/></QueryClientProvider>);expect(await screen.findByText('Decision recorded and audit-locked')).toBeTruthy();expect(screen.getByText('Evidence ZIP downloaded · access revoked')).toBeTruthy();expect(screen.getByText('RECORDED')).toBeTruthy();expect(screen.queryByText('REQUIRED')).toBeNull();expect(screen.queryByRole('button',{name:'Download evidence ZIP · one time'})).toBeNull()})
 it('keeps the exact imported backend run active without refetching stale workflow data',async()=>{const imported={...run,id:12,inputs_json:{...run.inputs_json,source_label:'manual-upload/customer-enterprise.json'},scenarios_json:[...run.scenarios_json,...Array.from({length:11},(_,index)=>({...run.scenarios_json[0],scenario_id:`customer-${index}`}))]};const fetchMock=vi.fn(async(input:RequestInfo|URL)=>{const url=String(input);let data:unknown=[];if(url.endsWith('/api/v1/demo/bootstrap'))data=run;else if(url.endsWith('/api/v1/workflows/import-json'))data=imported;else if(url.includes('/telemetry'))data=telemetry;else if(url.includes('/evidence')||url.includes('/timeline')||url.includes('/agents'))data=[];return {ok:true,json:async()=>data} as Response});vi.stubGlobal('fetch',fetchMock);render(<QueryClientProvider client={new QueryClient()}><App/></QueryClientProvider>);fireEvent.change(await screen.findByLabelText('Upload operational JSON'),{target:{files:[new File(['{"telemetry":[]}'],'customer-enterprise.json',{type:'application/json'})]}});expect(await screen.findByText('customer-enterprise.json')).toBeTruthy();expect(await screen.findByText(/Analysis run #12 is displayed/)).toBeTruthy();expect(screen.getByText('ACTIVE BACKEND ANALYSIS')).toBeTruthy();expect(fetchMock.mock.calls.filter(([input])=>String(input).endsWith('/api/v1/demo/bootstrap'))).toHaveLength(1)});
});
