import {useEffect,useMemo,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Activity,BrainCircuit,Building2,CheckCircle2,ChevronLeft,ChevronRight,Clock3,Compass,Database,Download,FileUp,FlaskConical,Network,Pause,Play,RefreshCw,ShieldCheck,Sparkles,TriangleAlert,Zap} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,Legend,Line,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {nexusApi} from './api/client';
import type {NexusRun} from './types';

async function bootstrap():Promise<NexusRun>{
 return nexusApi.bootstrap();
}

const GUIDE=[
 {id:'time-travel',label:'See the signal',title:'Tomorrow, before the alert',body:'Travel from the healthy baseline to the predicted Redis crossing. The reactive alert remains quiet until customers are already at risk.'},
 {id:'forecast',label:'Understand the forecast',title:'Transparent prediction',body:'The bounded forecast exposes its equation, safe threshold, residual error and assumptions. Confidence is evidence strength, not probability.'},
 {id:'twin',label:'Change the future',title:'A real interactive Digital Twin',body:'Explore Mode lets you change traffic, capacity, replicas and dependency latency, then persist and replay a new deterministic run.'},
 {id:'scenarios',label:'Stress the plan',title:'Twelve deterministic scenarios',body:'The same hashed Twin is replayed across growth, failure, rollback, rate limiting, cache correction and configuration drift.'},
 {id:'tournament',label:'Reject the false fix',title:'Eligibility overrides score',body:'FAST looks attractive, but fails a mandatory failover gate. A failed safety gate can never be outweighed by a high score.'},
 {id:'approval',label:'Keep humans accountable',title:'Stop at the decision boundary',body:'The final recommendation waits for an explicit human decision. Guided Demo never approves and never executes production action.'},
] as const;

export default function App(){
 const queryClient=useQueryClient();const [time,setTime]=useState(0);const [traffic,setTraffic]=useState(1);const [capacity,setCapacity]=useState(12000);const [replicas,setReplicas]=useState(4);const [latency,setLatency]=useState(20);
 const [mode,setMode]=useState<'overview'|'guided'|'explore'>('overview');const [guideStep,setGuideStep]=useState(0);const [guidePlaying,setGuidePlaying]=useState(false);const [scenarioId,setScenarioId]=useState('');const [uploadMessage,setUploadMessage]=useState('');
 const runQuery=useQuery({queryKey:['nexus-workflow'],queryFn:bootstrap});const run=runQuery.data;
 const telemetryQuery=useQuery({queryKey:['nexus-telemetry',run?.id],queryFn:()=>nexusApi.telemetry(run!.id),enabled:!!run});
 const evidenceQuery=useQuery({queryKey:['nexus-evidence',run?.id],queryFn:()=>nexusApi.evidence(run!.id),enabled:!!run});
 const timelineQuery=useQuery({queryKey:['nexus-timeline',run?.id],queryFn:()=>nexusApi.timeline(run!.id),enabled:!!run});
 const agentsQuery=useQuery({queryKey:['nexus-agents',run?.id],queryFn:()=>nexusApi.agents(run!.id),enabled:!!run});
 const rerun=useMutation({mutationFn:async()=>{const created=await nexusApi.create({traffic_multiplier:traffic,redis_capacity:capacity,application_replicas:replicas,dependency_latency_ms:latency,failover_state:'primary',seed:20260808,business:{conversion_rate:.034,average_order_value_inr:3200,risk_window_minutes:60,projected_failure_rate:.18,sla_penalty_inr:250000}});return nexusApi.runAll(created.id)},onSuccess:()=>queryClient.invalidateQueries()});
 const reset=useMutation({mutationFn:async()=>{await nexusApi.reset();const seeded=await nexusApi.seed();return nexusApi.runAll(seeded.id)},onSuccess:()=>queryClient.invalidateQueries()});
 const approve=useMutation({mutationFn:()=>nexusApi.approve(run!.id),onSuccess:()=>queryClient.invalidateQueries()});
 const exportEvidence=useMutation({mutationFn:()=>nexusApi.downloadEvidence(run!.id),onSuccess:()=>queryClient.invalidateQueries()});
 const telemetry=telemetryQuery.data??[];const point=useMemo(()=>telemetry.reduce((best,row)=>Math.abs(row.minute-time)<Math.abs(best.minute-time)?row:best,telemetry[0]),[telemetry,time]);
 const selectedScenario=run?.scenarios_json.find(s=>s.scenario_id===(scenarioId||run.scenarios_json[0]?.scenario_id));
 useEffect(()=>{if(mode!=='guided')return;document.getElementById(GUIDE[guideStep].id)?.scrollIntoView({behavior:'smooth',block:'center'})},[mode,guideStep]);
 useEffect(()=>{if(mode!=='guided'||!guidePlaying)return;const timer=window.setTimeout(()=>{if(guideStep<GUIDE.length-1)setGuideStep(x=>x+1);else setGuidePlaying(false)},8500);return()=>window.clearTimeout(timer)},[mode,guidePlaying,guideStep]);
 const startGuide=()=>{setMode('guided');setGuideStep(0);setGuidePlaying(true)};
 const enterExplore=()=>{setMode('explore');setGuidePlaying(false);document.getElementById('twin')?.scrollIntoView({behavior:'smooth',block:'start'})};
 const importEvidence=async(file?:File)=>{if(!file||!run)return;setUploadMessage('Validating and hashing evidence...');try{const content=await file.text();const parsed=JSON.parse(content);const controls=parsed.controls??parsed;const imported={traffic:Number(controls.traffic_multiplier),capacity:Number(controls.redis_capacity),replicas:Number(controls.application_replicas),latency:Number(controls.dependency_latency_ms)};if(!Number.isFinite(imported.traffic)||imported.traffic<.5||imported.traffic>10||!Number.isInteger(imported.capacity)||imported.capacity<6000||imported.capacity>50000||!Number.isInteger(imported.replicas)||imported.replicas<1||imported.replicas>20||!Number.isInteger(imported.latency)||imported.latency<0||imported.latency>500)throw new Error('JSON controls are missing or outside the displayed bounds.');setTraffic(imported.traffic);setCapacity(imported.capacity);setReplicas(imported.replicas);setLatency(imported.latency);await nexusApi.uploadEvidence(run.id,{filename:file.name,category:'configuration',content});await Promise.all([evidenceQuery.refetch(),timelineQuery.refetch()]);setUploadMessage('Evidence persisted. Review imported controls, then click Rerun bounded twin.')}catch(error){setUploadMessage(error instanceof Error?error.message:'Upload failed')}};
 if(runQuery.isLoading)return <LoadingScreen/>;
 if(!run)return <div className="error-state"><h1>SentinelOps Nexus could not reach its API.</h1><button onClick={()=>runQuery.refetch()}>Retry</button></div>;
 const forecast=run.forecast_json;const impact=run.impact_json;const twin=run.twin_json;const tournament=run.tournament_json;const candidates=tournament.candidates??[];const winner=candidates.find(c=>c.candidate_id===tournament.recommended_candidate_id);const money=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(impact.revenue_exposure_inr??0);
 const health=Math.max(0,Math.round(100-(point?.redis_memory_pct??72)*.42-(point?.queue_depth??0)*.03));
 return <div className="nexus-shell"><aside><div className="brand"><ShieldCheck/><b>SENTINEL<span>OPS NEXUS</span></b></div><div className="twin-tag">ENTERPRISE OPERATIONAL DIGITAL TWIN</div><div className="ready ok"><i/>WORKFLOW {run.state}</div><p className="eyebrow">AGENT WORKFORCE</p>{(agentsQuery.data??[]).map((a,i)=><a className="agent-link" href={`#${a.agent_id==='human-approval-gateway'?'approval':a.agent_id}`} key={`${a.agent_id}-${i}`}><i>{String(i+1).padStart(2,'0')}</i><span><b>{a.agent_name}</b><small>{a.output_type}</small></span></a>)}<div className="no-deploy"><ShieldCheck/> HUMAN CONTROL<br/><b>PRODUCTION ACTION: NOT EXECUTED</b></div></aside><main>
 <header><div><p className="eyebrow">B2B SERVICES - LATE BOTTLENECK DETECTION</p><h1>Predict tomorrow's bottleneck before customers experience it.</h1></div><button className="utility" onClick={()=>reset.mutate()} disabled={reset.isPending}><RefreshCw/>Reset demo</button></header>
 <section className="mode-switcher" aria-label="Demo modes"><div><span>CHOOSE YOUR VIEW</span><b>{mode==='guided'?'Guided Demo':mode==='explore'?'Explore Mode':'Command Centre'}</b><small>{mode==='guided'?'A six-stop, evidence-backed tour. No approval is automated.':mode==='explore'?'Change bounded inputs, rerun the Twin, and inspect every result.':'Start the story in one click or investigate freely.'}</small></div><div className="mode-actions"><button className={mode==='guided'?'active':''} onClick={startGuide}><Play/>One-click Guided Demo</button><button className={mode==='explore'?'active':''} onClick={enterExplore}><Compass/>Explore Mode</button></div></section>
 <section className="nexus-hero"><div><span className="risk"><TriangleAlert/> PREDICTED BOTTLENECK</span><h2>Payment Service - Redis saturation</h2><p>Safe capacity is forecast to cross in <b>{forecast.predicted_crossing_minutes} minutes</b>, before the reactive customer alert.</p></div><div className="countdown"><small>TIME TO CUSTOMER IMPACT</small><strong>{forecast.predicted_customer_impact_minutes}:00</strong><span>{forecast.confidence_label} heuristic evidence score - {forecast.heuristic_evidence_score}/100</span></div></section>
 <div className="kpi-grid nexus-kpis"><K title="Operational health" value={`${health}/100`}/><K title="Revenue exposure estimate" value={money}/><K title="Customers at risk" value={Number(impact.customers_at_risk??0).toLocaleString('en-IN')}/><K title="SLO risk" value={impact.sla_breach_risk_label??'Pending'}/><K title="Recommended" value={winner?.name??'Pending'}/><K title="Production action" value="NOT EXECUTED"/></div>
 <Panel id="time-travel" icon={<Clock3/>} title="Yesterday - Now - Tomorrow" subtitle="Real backend telemetry under one deterministic seed"><div className="time-controls"><span>Yesterday</span><input aria-label="Time travel" type="range" min="-1440" max="45" step="15" value={time} onChange={e=>setTime(Number(e.target.value))}/><span>+45 min</span><b>{point?.label}</b></div><div className="time-snapshot"><K title="Redis memory" value={`${point?.redis_memory_pct??0}%`}/><K title="Checkout p95" value={`${point?.p95_ms??0} ms`}/><K title="Queue depth" value={String(point?.queue_depth??0)}/><K title="Reactive alert" value={point?.reactive_alert?'ACTIVE':'NOT ACTIVE'}/></div><div className="chart"><ResponsiveContainer width="100%" height={260}><AreaChart data={telemetry}><CartesianGrid stroke="#163047"/><XAxis dataKey="label" stroke="#6f8ca4"/><YAxis stroke="#6f8ca4"/><Tooltip/><Legend/><Area type="monotone" dataKey="redis_memory_pct" stroke="#22d3ee" fill="#22d3ee33"/><Line type="monotone" dataKey="queue_depth" stroke="#fb7185"/></AreaChart></ResponsiveContainer></div></Panel>
 <div className="two"><Panel id="forecast" icon={<Activity/>} title="Forecast and Time-to-Impact" subtitle="Transparent bounded linear saturation trend"><div className="brief"><b>Equation</b><p>{forecast.equation}</p><b>Threshold and error</b><p>{forecast.safe_threshold_pct}% safe-capacity threshold; residual MAE {forecast.residual_mae}; error bound +/- {forecast.error_bound_minutes} minutes.</p><b>Assumptions</b>{(forecast.assumptions??[]).map((x:string)=><p key={x}>- {x}</p>)}</div></Panel><Panel id="impact" icon={<Building2/>} title="Business Impact" subtitle="Operational estimate under displayed assumptions"><div className="impact-number">{money}</div><p>{impact.formula}</p>{Object.entries(impact.inputs??{}).map(([key,value])=><div className="assumption" key={key}><span>{key.replaceAll('_',' ')}</span><b>{Number(value).toLocaleString('en-IN')}</b></div>)}<small>{impact.disclaimer}</small></Panel></div>
 <Panel id="evidence" icon={<Network/>} title="Evidence Explorer" subtitle="Each material claim cites persisted, hashed evidence">{(evidenceQuery.data??[]).map(e=><article className="evidence-row" key={e.evidence_id}><span>{e.evidence_id}</span><div><b>{e.source}</b><p>{e.summary}</p></div><strong>{e.content_hash.slice(0,10)}</strong></article>)}</Panel>
 <Panel id="agents" icon={<BrainCircuit/>} title="Agent Activity Trace" subtitle="Structured outputs only; no hidden chain-of-thought"><div className="agent-flow">{(agentsQuery.data??[]).map((a,i)=><article id={a.agent_id} key={`${a.agent_id}-${i}`}><i>{i+1}</i><b>{a.agent_name}</b><small>{a.output_type}</small><em>{a.evidence_ids.length} evidence links</em></article>)}</div></Panel>
 <Panel id="twin" icon={<Database/>} title="Digital Twin Controls" subtitle="A bounded operational model under documented assumptions"><div className="manifest nexus-manifest"><K title="Twin" value={String(twin.twin_id??'pending')}/><K title="Seed" value={String(twin.random_seed??run.seed)}/><K title="Network" value={String(twin.network_policy??'disabled').toUpperCase()}/><K title="Manifest hash" value={String(twin.manifest_hash??'').slice(0,14)}/><K title="Scenarios" value={String(run.scenarios_json.length)}/><K title="Source revision" value={String(twin.source_revision??'').slice(0,10)}/></div><div className="preset-row"><span>EXPLORATION PRESETS</span><button onClick={()=>{setTraffic(1);setCapacity(12000);setReplicas(4);setLatency(20)}}>Baseline</button><button onClick={()=>{setTraffic(10);setCapacity(12000);setReplicas(4);setLatency(80)}}>10x traffic</button><button onClick={()=>{setTraffic(1.5);setCapacity(6000);setReplicas(2);setLatency(250)}}>Constrained</button><button onClick={()=>{setTraffic(2);setCapacity(50000);setReplicas(12);setLatency(10)}}>Resilient</button></div><div className="upload-row"><label><FileUp/>Upload operational JSON<input aria-label="Upload operational JSON" type="file" accept="application/json,.json" onChange={e=>void importEvidence(e.target.files?.[0])}/></label><span>Accepts a controls object or a nested controls object, up to 256 KB.</span></div>{uploadMessage&&<div className="upload-status" role="status">{uploadMessage}</div>}<div className="sim-controls"><Control label="Traffic multiplier" value={traffic} min={.5} max={10} step={.5} set={setTraffic}/><Control label="Redis capacity" value={capacity} min={6000} max={50000} step={1000} set={setCapacity}/><Control label="Application replicas" value={replicas} min={1} max={20} step={1} set={setReplicas}/><Control label="Dependency latency ms" value={latency} min={0} max={500} step={10} set={setLatency}/></div><button className="primary" onClick={()=>rerun.mutate()} disabled={rerun.isPending}><FlaskConical/>{rerun.isPending?'Running 12 scenarios...':'Rerun bounded twin'}</button><small className="run-safety">Creates a new persisted simulation only. PRODUCTION ACTION: NOT EXECUTED.</small></Panel>
 <Panel id="scenarios" icon={<FlaskConical/>} title="Scenario Lab" subtitle="Select and inspect twelve deterministic future, chaos, and counterfactual scenarios"><div className="scenario-explorer"><div className="scenario-table"><div className="scenario-head"><b>Scenario</b><b>Status</b><b>p95</b><b>Error</b><b>Hash</b></div>{run.scenarios_json.map(s=><button className={`scenario-row ${selectedScenario?.scenario_id===s.scenario_id?'selected':''}`} onClick={()=>setScenarioId(s.scenario_id)} key={s.scenario_id}><span>{s.name}</span><i className={s.status}>{s.status}</i><i>{s.p95_ms} ms</i><i>{s.error_rate_pct}%</i><i>{s.result_hash.slice(0,8)}</i></button>)}</div>{selectedScenario&&<article className="scenario-detail"><span>SELECTED SCENARIO</span><h3>{selectedScenario.name}</h3><K title="Bottleneck avoided" value={selectedScenario.bottleneck_avoided?'YES':'NO'}/><K title="Recovery" value={`${selectedScenario.recovery_minutes} min`}/><K title="Deterministic hash" value={selectedScenario.result_hash.slice(0,16)}/><pre>{JSON.stringify(selectedScenario.inputs,null,2)}</pre></article>}</div></Panel>
 <Panel id="tournament" icon={<Zap/>} title="Intervention Tournament" subtitle="Eligibility overrides score; one failed mandatory gate disqualifies"><div className="strategy-grid">{candidates.map((c,i)=><article className={c.candidate_id===tournament.recommended_candidate_id?'winner':''} key={c.candidate_id}><header><span>#{i+1} - {c.name}</span><strong>{c.score}</strong></header><h3>{c.action}</h3><div className="strategy-metrics"><small>Risk <b>{c.risk_score}/100</b></small><small>Recovery <b>{c.recovery_minutes} min</b></small><small>Cost <b>{new Intl.NumberFormat('en-IN').format(c.cost_estimate_inr)}</b></small></div><div className="mini-gates">{c.gates.map(g=><span className={g.passed?'pass':'fail'} title={g.details} key={g.gate}>{g.passed?<CheckCircle2/>:<TriangleAlert/>}{g.gate}</span>)}</div><em>{c.eligible?'ELIGIBLE':'DISQUALIFIED'}</em><p>{c.verdict}</p></article>)}</div></Panel>
 <div className="two"><Panel id="executive" icon={<Sparkles/>} title="Executive Decision Brief" subtitle="Evidence-backed recommendation with uncertainty"><div className="brief"><b>Finding</b><p>{run.recommendation_json.summary}</p><b>Recommendation</b><p>{run.recommendation_json.recommendation}</p><b>Contradictory evidence</b>{(run.recommendation_json.contradictory_evidence??[]).map((x:string)=><p key={x}>- {x}</p>)}</div></Panel><Panel id="approval" icon={<ShieldCheck/>} title="Human Approval Gateway" subtitle="Approval exports evidence; it never executes a production change"><div className="approval-x"><span>{run.state==='DECIDED'?'HUMAN DECISION RECORDED':'AWAITING HUMAN'}</span><h2>{winner?.name}</h2><p>{winner?.action}</p><button disabled={run.state==='DECIDED'||approve.isPending} onClick={()=>approve.mutate()}>{run.state==='DECIDED'?'Decision already recorded':'Approve proposal'}</button>{run.state==='DECIDED'&&!run.human_decision_json.exported_at&&<button className="primary" disabled={exportEvidence.isPending} onClick={()=>exportEvidence.mutate()}><Download/>{exportEvidence.isPending?'Preparing evidence...':'Export evidence ZIP once'}</button>}{run.human_decision_json.exported_at&&<strong className="export-consumed">Evidence ZIP downloaded · access revoked</strong>}{exportEvidence.isError&&<strong className="export-error">{exportEvidence.error.message}</strong>}<small>PRODUCTION ACTION: NOT EXECUTED</small></div></Panel></div>
 <Panel id="audit" icon={<ShieldCheck/>} title="Tamper-Evident Audit Timeline" subtitle="Chained SHA-256 events persisted by backend policy">{(timelineQuery.data??[]).map(e=><div className="timeline-row" key={e.sequence}><i/><b>{e.event_type}</b><span>{e.actor}</span><code>{e.event_hash.slice(0,12)}</code></div>)}</Panel>
 <div className="safety-strip"><span><CheckCircle2/> Forecast calculated <b>YES</b></span><span><CheckCircle2/> FAST disqualified <b>YES</b></span><span><ShieldCheck/> Human approval <b>REQUIRED</b></span><span><ShieldCheck/> Production action <b>NOT EXECUTED</b></span></div>
 {mode==='guided'&&<div className="guide-card" role="dialog" aria-live="polite" aria-label="Guided Demo"><div className="guide-progress"><span style={{width:`${((guideStep+1)/GUIDE.length)*100}%`}}/></div><small>{GUIDE[guideStep].label.toUpperCase()} · {guideStep+1}/{GUIDE.length}</small><h2>{GUIDE[guideStep].title}</h2><p>{GUIDE[guideStep].body}</p><div><button aria-label="Previous guided step" disabled={guideStep===0} onClick={()=>setGuideStep(x=>x-1)}><ChevronLeft/></button><button aria-label={guidePlaying?'Pause guided demo':'Play guided demo'} onClick={()=>setGuidePlaying(x=>!x)}>{guidePlaying?<Pause/>:<Play/>}</button><button aria-label="Next guided step" disabled={guideStep===GUIDE.length-1} onClick={()=>setGuideStep(x=>x+1)}><ChevronRight/></button><button className="exit-guide" onClick={()=>{setMode('overview');setGuidePlaying(false)}}>Exit tour</button></div><strong>PRODUCTION ACTION: NOT EXECUTED</strong></div>}
 </main></div>
}

function Panel({id,icon,title,subtitle,children}:{id:string;icon:React.ReactNode;title:string;subtitle:string;children:React.ReactNode}){return <section className="panel" id={id}><header><div className="panel-title">{icon}<div><h2>{title}</h2><p>{subtitle}</p></div></div></header>{children}</section>}
function K({title,value}:{title:string;value:string}){return <div className="kpi"><span>{title}</span><b>{value}</b></div>}
function Control({label,value,min,max,step,set}:{label:string;value:number;min:number;max:number;step:number;set:(value:number)=>void}){return <label>{label}<b>{value.toLocaleString()}</b><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>set(Number(e.target.value))}/></label>}
function LoadingScreen(){const [seconds,setSeconds]=useState(0);useEffect(()=>{const timer=window.setInterval(()=>setSeconds(value=>value+1),1000);return()=>window.clearInterval(timer)},[]);const message=seconds<8?'Connecting to the operational API...':seconds<35?'Render is waking the API service...':'Free-tier wake-up can take about a minute. Your request is still active.';return <div className="nexus-loading"><ShieldCheck/><h1>SentinelOps Nexus</h1><p>{message}</p><div className="loading-track"><i/></div><small>{seconds}s · PRODUCTION ACTION: NOT EXECUTED</small></div>}
