import {useMemo,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Activity,BrainCircuit,Building2,CheckCircle2,Clock3,Database,FlaskConical,Network,ShieldCheck,Sparkles,TriangleAlert,Zap} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,Legend,Line,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {api} from './api/client';

export default function App(){
 const [load,setLoad]=useState(1);const [capacity,setCapacity]=useState(12000);const [time,setTime]=useState(0);
 const twin=useQuery({queryKey:['nexus',load,capacity],queryFn:()=>api.nexus(load,capacity)});const d=twin.data;
 const point=useMemo(()=>d?.telemetry.reduce((best,row)=>Math.abs(row.minute-time)<Math.abs(best.minute-time)?row:best,d.telemetry[0]),[d,time]);
 if(twin.isLoading)return <div className="nexus-loading">Building the operational Digital Twin…</div>;
 if(!d)return <div className="error-state"><h1>SentinelOps Nexus could not reach its predictive API.</h1><button onClick={()=>twin.refetch()}>Retry</button></div>;
 const money=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(d.business_impact.revenue_risk_inr);
 return <div className="nexus-shell"><aside><div className="brand"><ShieldCheck/><b>SENTINEL<span>OPS NEXUS</span></b></div><div className="twin-tag">THE ENTERPRISE OPERATIONAL DIGITAL TWIN</div><div className="ready ok"><i/>PREDICTIVE TWIN LIVE</div><p className="eyebrow">WORKFORCE</p>{d.agents.map((a,i)=><a className="agent-link" href={`#${a.id}`} key={a.id}><i>{String(i+1).padStart(2,'0')}</i><span><b>{a.name}</b><small>{a.result}</small></span></a>)}<div className="no-deploy"><ShieldCheck/> HUMAN CONTROL<br/><b>NO AUTO-EXECUTION</b></div></aside><main><header><div><p className="eyebrow">THE ENTERPRISE OPERATIONAL DIGITAL TWIN</p><h1>Predict tomorrow’s bottleneck before customers feel it.</h1></div><div className="live"><i/> LIVE · SEEDED · SAFE</div></header>
 <section className="nexus-hero"><div><span className="risk"><TriangleAlert/> BOTTLENECK FORECAST</span><h2>{d.prediction.service}</h2><p>{d.prediction.bottleneck} is projected to breach its safe operating threshold in <b>{d.prediction.time_to_impact_minutes} minutes</b>.</p></div><div className="countdown"><small>TIME TO IMPACT</small><strong>{d.prediction.time_to_impact_minutes}:00</strong><span>{d.prediction.confidence_label} evidence confidence · {d.prediction.confidence_score}/100*</span></div></section>
 <div className="kpi-grid nexus-kpis"><K title="Reliability Score" value={`${d.reliability_score}/100`}/><K title="Revenue Exposure" value={money}/><K title="Customers Exposed" value={d.business_impact.customers_exposed.toLocaleString('en-IN')}/><K title="Predicted Cause" value={d.prediction.bottleneck}/><K title="Human Approval" value="REQUIRED"/><K title="Execution" value="NOT EXECUTED"/></div>
 <Panel id="time-travel" icon={<Clock3/>} title="Time Travel" subtitle="Yesterday · now · tomorrow, calculated from the same telemetry window"><div className="time-controls"><span>−30 min</span><input aria-label="Time travel" type="range" min="-30" max="30" step="10" value={time} onChange={e=>setTime(Number(e.target.value))}/><span>+30 min</span><b>{time===0?'NOW':time>0?`TOMORROW +${time} MIN`:`HISTORY ${time} MIN`}</b></div><div className="time-snapshot"><K title="Redis saturation" value={`${point?.redis_saturation}%`}/><K title="Checkout p95" value={`${point?.checkout_p95_ms} ms`}/><K title="Queue depth" value={String(point?.queue_depth)}/><K title="Error rate" value={`${point?.error_rate}%`}/></div><div className="chart"><ResponsiveContainer width="100%" height={260}><AreaChart data={d.telemetry}><defs><linearGradient id="sat" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#22d3ee" stopOpacity={.45}/><stop offset="95%" stopColor="#22d3ee" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#163047"/><XAxis dataKey="minute" stroke="#6f8ca4"/><YAxis stroke="#6f8ca4"/><Tooltip/><Legend/><Area type="monotone" dataKey="redis_saturation" stroke="#22d3ee" fill="url(#sat)"/><Line type="monotone" dataKey="queue_depth" stroke="#fb7185"/></AreaChart></ResponsiveContainer></div></Panel>
 <div className="two"><Panel id="evidence" icon={<Network/>} title="Evidence Graph" subtitle="Every forecast claim remains traceable">{d.evidence.map(e=><article className="evidence-row" key={e.id}><span>{e.id}</span><div><b>{e.source}</b><p>{e.claim}</p></div><strong>{String(e.value)}</strong></article>)}</Panel><Panel id="impact" icon={<Building2/>} title="Business Impact Agent" subtitle="Estimate—not guaranteed loss"><div className="impact-number">{money}</div><p>Estimated revenue exposure across {d.business_impact.assumptions.risk_window_minutes} minutes.</p>{Object.entries(d.business_impact.assumptions).map(([k,v])=><div className="assumption" key={k}><span>{k.replaceAll('_',' ')}</span><b>{k==='conversion_rate'?`${Number(v)*100}%`:Number(v).toLocaleString('en-IN')}</b></div>)}<small>Change these assumptions in production integrations; they are shown to prevent false precision.</small></Panel></div>
 <Panel id="agents" icon={<BrainCircuit/>} title="Multi-Agent Reasoning Trace" subtitle="Typed hand-offs; backend policy owns state transitions"><div className="agent-flow">{d.agents.map((a,i)=><article id={a.id} key={a.id}><i>{i+1}</i><b>{a.name}</b><small>{a.result}</small><em>{a.evidence_ids.length} evidence links</em></article>)}</div></Panel>
 <Panel id="twin" icon={<Database/>} title="Digital Twin Manifest" subtitle="Identical seed, evidence and network policy for every intervention"><div className="manifest nexus-manifest"><K title="Seed" value={String(d.manifest.seed)}/><K title="Network" value={d.manifest.network_policy.toUpperCase()}/><K title="Model" value={d.manifest.model}/><K title="Telemetry hash" value={d.manifest.telemetry_hash.slice(0,14)+'…'}/><K title="Configuration hash" value={d.manifest.configuration_hash.slice(0,14)+'…'}/><K title="Manifest hash" value={d.manifest.manifest_hash.slice(0,14)+'…'}/></div><div className="sim-controls"><label>Traffic multiplier <b>{load.toFixed(1)}×</b><input type="range" min="0.5" max="2" step="0.1" value={load} onChange={e=>setLoad(Number(e.target.value))}/></label><label>Redis capacity <b>{capacity.toLocaleString()}</b><input type="range" min="6000" max="24000" step="1000" value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label></div></Panel>
 <Panel id="chaos" icon={<FlaskConical/>} title="Chaos Simulator" subtitle="What if Redis crashes, latency doubles, or one million users arrive?"><div className="scenario-table"><div className="scenario-head"><b>Scenario</b><b>Baseline</b><b>Fast</b><b>Safe</b><b>Optimal</b></div>{d.chaos_scenarios.map(s=><div className="scenario-row" key={s.name}><span>{s.name}</span>{['baseline','fast','safe','optimal'].map(k=><i className={String(s[k as keyof typeof s])} key={k}>{s[k as keyof typeof s]}</i>)}</div>)}</div></Panel>
 <Panel id="tournament" icon={<Zap/>} title="Intervention Tournament" subtitle="Three plausible strategies · failed mandatory gate means ineligible"><div className="strategy-grid">{d.strategies.map((s,i)=><article className={s.id===d.recommended_strategy.id?'winner':''} key={s.id}><header><span>#{i+1} · {s.name}</span><strong>{s.score}</strong></header><h3>{s.action}</h3><div className="strategy-metrics"><small>Risk <b>{s.risk}/100</b></small><small>Recovery <b>{s.recovery_minutes} min</b></small><small>Cost <b>+{s.cost_delta_pct}%</b></small></div><div className="mini-gates">{Object.entries(s.gates).map(([g,pass])=><span className={pass?'pass':'fail'} key={g}>{pass?<CheckCircle2/>:<TriangleAlert/>}{g}</span>)}</div><em>{s.eligible?'ELIGIBLE':'DISQUALIFIED'}</em></article>)}</div></Panel>
 <div className="two"><Panel id="executive" icon={<Sparkles/>} title="Executive Copilot" subtitle="Plain-language decision brief"><div className="brief"><b>What is happening?</b><p>Redis capacity on the payment path is forecast to cross its safe threshold before current customer-facing alerts fire.</p><b>What should we do?</b><p>{d.recommended_strategy.action}. It passed all mandatory Twin scenarios and has the strongest transparent score.</p><b>What remains uncertain?</b><p>Demand, conversion and order-value assumptions may change. Confidence is evidence-labelled, not a guaranteed probability.</p></div></Panel><Panel id="approval" icon={<ShieldCheck/>} title="Human Decision" subtitle="SentinelOps Nexus cannot approve or execute its recommendation"><div className="approval-x"><span>RECOMMENDED</span><h2>{d.recommended_strategy.name}</h2><p>{d.recommended_strategy.action}</p><button disabled>Approve intervention</button><button disabled>Reject</button><small>Demo controls are intentionally locked. No production connector is configured.</small></div></Panel></div>
 <div className="safety-strip"><span><CheckCircle2/> Prediction generated <b>YES</b></span><span><CheckCircle2/> Evidence linked <b>YES</b></span><span><ShieldCheck/> Human approval <b>REQUIRED</b></span><span><ShieldCheck/> Production action <b>NOT EXECUTED</b></span></div><p className="footnote">* {d.prediction.confidence_note}</p>
 </main></div>}
function Panel({id,icon,title,subtitle,children}:{id:string;icon:React.ReactNode;title:string;subtitle:string;children:React.ReactNode}){return <section className="panel" id={id}><header><div className="panel-title">{icon}<div><h2>{title}</h2><p>{subtitle}</p></div></div><button className="evidence-btn">Show evidence</button></header>{children}</section>}
function K({title,value}:{title:string;value:string}){return <div className="kpi"><span>{title}</span><b>{value}</b></div>}
