import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,describe,expect,it,vi} from 'vitest';
import LandingPage from './pages/LandingPage';
import ApprovalPage from './pages/ApprovalPage';
import AgentPage from './pages/AgentPage';
import ResourcePage from './pages/ResourcePage';
import JudgeDemoPage from './pages/JudgeDemoPage';

const run={id:7,state:'AWAITING_HUMAN',tournament_json:{recommended_candidate_id:'optimal',candidates:[{candidate_id:'optimal',eligible:true,gates:[{mandatory:true,passed:true}]}]}};
const agentNames=['nexus-orchestrator','observer-agent','evidence-agent','process-discovery-agent','prediction-agent','digital-twin-agent','simulation-agent','optimization-agent','verification-agent','business-impact-agent','executive-agent'];
const agents=agentNames.map(agent_name=>({agent_name,display_name:agent_name.replaceAll('-',' '),purpose:'Backend-operated agent',responsibilities:['persist results'],current_status:'COMPLETED',workflow_id:7,last_execution_time:'2026-08-05',execution_duration_ms:12,input_artifact:{workflow_id:7},output_artifact:{status:'ok'},evidence_references:['ev-config'],assumptions:[],errors:null,retry_count:0,result_hash:'a'.repeat(64),supported_actions:['view_details','view_inputs','view_outputs','view_evidence','run','rerun','view_audit_events'],reasoning_summary:'Structured evidence summary'}));
afterEach(()=>{cleanup();vi.restoreAllMocks();history.replaceState({},'','/')});
const wrap=(node:React.ReactNode)=>render(<QueryClientProvider client={new QueryClient()}>{node}</QueryClientProvider>);

describe('upgrade routes and authorization UX',()=>{
 it('renders the fast product landing page and safety boundary',()=>{wrap(<LandingPage/>);expect(screen.getByText('Predict tomorrow’s operational bottleneck before customers experience it.')).toBeTruthy();expect(screen.getByText('PRODUCTION ACTION: NOT EXECUTED')).toBeTruthy();expect(screen.getByRole('button',{name:/Open Command Centre/})).toBeTruthy()});
 it('shows Intern role and keeps approval disabled',async()=>{history.replaceState({},'','/workflows/7/approval');vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>({ok:true,json:async()=>String(input).includes('verify-role')?{verified:true,role:'INTERN',permissions:['reject'],expires_at:'2026-08-05',verification_token:'signed-token-value'}:[run]}) as Response));wrap(<ApprovalPage/>);fireEvent.change(screen.getByLabelText('Actor name'),{target:{value:'Intern User'}});fireEvent.change(screen.getByLabelText('Trial access code'),{target:{value:'0000'}});fireEvent.click(screen.getByRole('button',{name:'Verify role'}));expect(await screen.findByText(/VERIFIED ROLE: INTERN/)).toBeTruthy();expect((screen.getByRole('button',{name:'Approve Recommendation'}) as HTMLButtonElement).disabled).toBe(true)});
 it('enables Senior Developer approval only after rationale',async()=>{history.replaceState({},'','/workflows/7/approval');vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>({ok:true,json:async()=>String(input).includes('verify-role')?{verified:true,role:'SENIOR_DEVELOPER',permissions:['approve'],expires_at:'2026-08-05',verification_token:'signed-token-value'}:[run]}) as Response));wrap(<ApprovalPage/>);fireEvent.change(screen.getByLabelText('Actor name'),{target:{value:'Senior User'}});fireEvent.change(screen.getByLabelText('Trial access code'),{target:{value:'1111'}});fireEvent.click(screen.getByRole('button',{name:'Verify role'}));await screen.findByText(/VERIFIED ROLE: SENIOR DEVELOPER/);expect((screen.getByRole('button',{name:'Approve Recommendation'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.change(screen.getByLabelText('Mandatory rationale'),{target:{value:'All gates reviewed.'}});await waitFor(()=>expect((screen.getByRole('button',{name:'Approve Recommendation'}) as HTMLButtonElement).disabled).toBe(false))});
 it('renders every workforce card as a clickable agent route',async()=>{history.replaceState({},'','/agents');vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>({ok:true,json:async()=>String(input).endsWith('/api/v1/workflows')?[run]:agents}) as Response));wrap(<AgentPage/>);for(const name of agentNames)expect((await screen.findByRole('link',{name:new RegExp(name.replaceAll('-',' '),'i')})).getAttribute('href')).toBe(`/agents/${name}`)});
 it('routes Run Agent and Re-run Agent through backend POST endpoints',async()=>{history.replaceState({},'','/agents/observer-agent');const fetchMock=vi.fn(async(input:RequestInfo|URL)=>{const url=String(input);return {ok:true,json:async()=>url.endsWith('/api/v1/workflows')?[run]:url.includes('/agents/observer-agent/')?agents[1]:agents} as Response});vi.stubGlobal('fetch',fetchMock);wrap(<AgentPage/>);fireEvent.click(await screen.findByRole('button',{name:'Run Agent'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/api/v1/workflows/7/agents/observer-agent/run'),expect.objectContaining({method:'POST'})));fireEvent.click(screen.getByRole('button',{name:/Re-run Agent/}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/api/v1/workflows/7/agents/observer-agent/rerun'),expect.objectContaining({method:'POST'})))});
 it('loads evidence, audit and verification route data from backend APIs',async()=>{history.replaceState({},'','/workflows/7/evidence');const fetchMock=vi.fn(async(input:RequestInfo|URL)=>({ok:true,json:async()=>String(input).endsWith('/api/v1/workflows')?[run]:[{evidence_id:'ev-config'}]}) as Response);vi.stubGlobal('fetch',fetchMock);wrap(<ResourcePage/>);expect(await screen.findByText(/ev-config/)).toBeTruthy();expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/api/v1/workflows/7/evidence'),expect.anything())});
 it('renders the judge demo from backend workflow and integration evidence',async()=>{history.replaceState({},'','/judge-demo');const fetchMock=vi.fn(async(input:RequestInfo|URL)=>{const url=String(input);let data:unknown=[];if(url.endsWith('/api/v1/workflows'))data=[run];else if(url.includes('/integrations/antigravity/status'))data={status:'BLOCKED_BY_PARTICIPANT_ACCESS',official_runtime_invoked:false,blocker:'Participant access unavailable',production_action:'NOT_EXECUTED'};else if(url.endsWith('/platform/integrations'))data=[{integration:'Gemini',status:'LOCAL_FALLBACK_AVAILABLE'}];return {ok:true,json:async()=>data} as Response});vi.stubGlobal('fetch',fetchMock);wrap(<JudgeDemoPage/>);expect(await screen.findByRole('heading',{name:'Judge Demo'})).toBeTruthy();expect(screen.getByText('20. Google Cloud evidence')).toBeTruthy();expect(screen.getAllByText('PRODUCTION ACTION: NOT EXECUTED').length).toBeGreaterThan(0);expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/api/v1/workflows'),expect.anything())});
});
