import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,describe,expect,it,vi} from 'vitest';
import LandingPage from './pages/LandingPage';
import ApprovalPage from './pages/ApprovalPage';
import AgentPage from './pages/AgentPage';
import ResourcePage from './pages/ResourcePage';
import JudgeDemoPage from './pages/JudgeDemoPage';

const candidate=(candidate_id:'fast'|'optimal',eligible:boolean)=>({candidate_id,name:candidate_id.toUpperCase(),action:candidate_id==='fast'?'Scale applications only':'Increase Redis capacity and correct cache policy',expected_benefit:'Bounded recovery',cost_estimate_inr:eligible?154000:42000,risk_score:eligible?9:32,recovery_minutes:eligible?6:4,reversible:eligible,assumptions:[],gates:[{gate:'failover_test',mandatory:true,passed:eligible,details:eligible?'Passed':'Failed',evidence_ids:['ev-gate']}],score_components:{safety:50},score:eligible?87.7:79.2,eligible,verdict:eligible?'Eligible':'Disqualified'});
const run={id:7,name:'Payment capacity forecast',state:'AWAITING_HUMAN',seed:20260808,inputs_json:{traffic_multiplier:1,redis_capacity:12000,application_replicas:4,dependency_latency_ms:20,failover_state:'primary',business:{}},forecast_json:{model_name:'bounded-linear-saturation',equation:'memory_pct(t) = 72 + 0.6 * minutes',safe_threshold_pct:90,predicted_crossing_minutes:30,predicted_customer_impact_minutes:45,residual_mae:0,error_bound_minutes:3,evidence_ids:['ev-telemetry']},twin_json:{twin_id:'twin-1',manifest_hash:'a'.repeat(64),source_revision:'abc123',random_seed:20260808,network_policy:'disabled',capacity_constraints:{redis_capacity:12000},evidence_references:['ev-config']},scenarios_json:[{scenario_id:'baseline',name:'Baseline Growth',inputs:{},status:'pass',bottleneck_avoided:true,p95_ms:240,error_rate_pct:.2,recovery_minutes:6,result_hash:'b'.repeat(64),evidence_ids:['ev-telemetry']}],tournament_json:{recommended_candidate_id:'optimal',candidates:[candidate('fast',false),candidate('optimal',true)],weights:{safety:.4},rule:'Eligibility overrides score',twin_id:'twin-1'},impact_json:{revenue_exposure_inr:27000000,estimated_recovery_minutes:6},recommendation_json:{summary:'Redis is the limiting resource',recommendation:'Recommend OPTIMAL',evidence_ids:['ev-gate']},human_decision_json:{},production_action_executed:false,created_at:'2026-08-05',updated_at:'2026-08-05'};
const agentNames=['nexus-orchestrator','observer-agent','evidence-agent','process-discovery-agent','prediction-agent','digital-twin-agent','simulation-agent','optimization-agent','verification-agent','business-impact-agent','executive-agent'];
const agents=agentNames.map(agent_name=>({agent_name,display_name:agent_name.replaceAll('-',' '),purpose:'Backend-operated agent',responsibilities:['persist results'],current_status:'COMPLETED',workflow_id:7,last_execution_time:'2026-08-05',execution_duration_ms:12,input_artifact:{workflow_id:7},output_artifact:{status:'ok'},evidence_references:['ev-config'],assumptions:[],errors:null,retry_count:0,result_hash:'a'.repeat(64),supported_actions:['view_details','view_inputs','view_outputs','view_evidence','run','rerun','view_audit_events'],reasoning_summary:'Structured evidence summary'}));
afterEach(()=>{cleanup();vi.restoreAllMocks();history.replaceState({},'','/')});
const wrap=(node:React.ReactNode)=>render(<QueryClientProvider client={new QueryClient()}>{node}</QueryClientProvider>);

describe('upgrade routes and authorization UX',()=>{
 it('renders the fast product landing page and safety boundary',()=>{wrap(<LandingPage/>);expect(screen.getByText('Predict tomorrow’s operational bottleneck before customers experience it.')).toBeTruthy();expect(screen.getByText('PRODUCTION ACTION: NOT EXECUTED')).toBeTruthy();expect(screen.getByRole('button',{name:/Open Command Centre/})).toBeTruthy()});
 it('shows Intern role and keeps approval disabled',async()=>{history.replaceState({},'','/workflows/7/approval');vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>({ok:true,json:async()=>String(input).includes('verify-role')?{verified:true,role:'INTERN',permissions:['reject'],expires_at:'2026-08-05',verification_token:'signed-token-value'}:[run]}) as Response));wrap(<ApprovalPage/>);fireEvent.change(screen.getByLabelText('Actor name'),{target:{value:'Intern User'}});fireEvent.change(screen.getByLabelText('Trial access code'),{target:{value:'0000'}});fireEvent.click(screen.getByRole('button',{name:'Verify role'}));expect(await screen.findByText(/VERIFIED ROLE: INTERN/)).toBeTruthy();expect((screen.getByRole('button',{name:'Approve Recommendation'}) as HTMLButtonElement).disabled).toBe(true)});
 it('enables Senior Developer approval only after rationale',async()=>{history.replaceState({},'','/workflows/7/approval');vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>({ok:true,json:async()=>String(input).includes('verify-role')?{verified:true,role:'SENIOR_DEVELOPER',permissions:['approve'],expires_at:'2026-08-05',verification_token:'signed-token-value'}:[run]}) as Response));wrap(<ApprovalPage/>);fireEvent.change(screen.getByLabelText('Actor name'),{target:{value:'Senior User'}});fireEvent.change(screen.getByLabelText('Trial access code'),{target:{value:'1111'}});fireEvent.click(screen.getByRole('button',{name:'Verify role'}));await screen.findByText(/VERIFIED ROLE: SENIOR DEVELOPER/);expect((screen.getByRole('button',{name:'Approve Recommendation'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.change(screen.getByLabelText('Mandatory rationale'),{target:{value:'All gates reviewed.'}});await waitFor(()=>expect((screen.getByRole('button',{name:'Approve Recommendation'}) as HTMLButtonElement).disabled).toBe(false))});
 it('renders every workforce card as a clickable agent route',async()=>{history.replaceState({},'','/agents');vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>({ok:true,json:async()=>String(input).endsWith('/api/v1/workflows')?[run]:agents}) as Response));wrap(<AgentPage/>);for(const name of agentNames)expect((await screen.findByRole('link',{name:new RegExp(name.replaceAll('-',' '),'i')})).getAttribute('href')).toBe(`/agents/${name}`)});
 it('routes Run Agent and Re-run Agent through backend POST endpoints',async()=>{history.replaceState({},'','/agents/observer-agent');const fetchMock=vi.fn(async(input:RequestInfo|URL)=>{const url=String(input);return {ok:true,json:async()=>url.endsWith('/api/v1/workflows')?[run]:url.includes('/agents/observer-agent/')?agents[1]:agents} as Response});vi.stubGlobal('fetch',fetchMock);wrap(<AgentPage/>);fireEvent.click(await screen.findByRole('button',{name:'Run Agent'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/api/v1/workflows/7/agents/observer-agent/run'),expect.objectContaining({method:'POST'})));fireEvent.click(screen.getByRole('button',{name:/Re-run Agent/}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/api/v1/workflows/7/agents/observer-agent/rerun'),expect.objectContaining({method:'POST'})))});
 it('loads evidence, audit and verification route data from backend APIs',async()=>{history.replaceState({},'','/workflows/7/evidence');const fetchMock=vi.fn(async(input:RequestInfo|URL)=>({ok:true,json:async()=>String(input).endsWith('/api/v1/workflows')?[run]:[{evidence_id:'ev-config'}]}) as Response);vi.stubGlobal('fetch',fetchMock);wrap(<ResourcePage/>);expect(await screen.findByText(/ev-config/)).toBeTruthy();expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/api/v1/workflows/7/evidence'),expect.anything())});
 it('makes all 20 judge stages clickable, keyboard navigable and deep-linkable',async()=>{history.replaceState({},'','/judge-demo?stage=scenario-progress');const fetchMock=mockJudgeFetch();vi.stubGlobal('fetch',fetchMock);wrap(<JudgeDemoPage/>);expect(await screen.findByRole('heading',{name:'Scenario progress'})).toBeTruthy();const tabs=screen.getAllByRole('tab');expect(tabs).toHaveLength(20);expect(location.search).toContain('stage=scenario-progress');for(const tab of tabs){fireEvent.click(tab);expect(tab.getAttribute('aria-selected')).toBe('true')}fireEvent.click(screen.getByRole('tab',{name:/Mandatory Safety Gates/}));expect(screen.getByRole('heading',{name:'Mandatory Safety Gates'})).toBeTruthy();expect(location.search).toContain('stage=mandatory-safety-gates');const active=screen.getByRole('tab',{name:/Mandatory Safety Gates/});fireEvent.keyDown(active,{key:'ArrowRight'});expect(screen.getByRole('heading',{name:'Verification result'})).toBeTruthy();expect(screen.getByRole('tab',{name:/Verification result/}).getAttribute('aria-selected')).toBe('true');expect(screen.getAllByText('PRODUCTION ACTION: NOT EXECUTED').length).toBeGreaterThan(0)});
 it('plays, pauses and restarts without ever calling an approval endpoint',async()=>{history.replaceState({},'','/judge-demo');const fetchMock=mockJudgeFetch();vi.stubGlobal('fetch',fetchMock);wrap(<JudgeDemoPage/>);await screen.findByRole('heading',{name:'Problem'});vi.useFakeTimers();fireEvent.click(screen.getByRole('button',{name:'Play guided mode'}));await vi.advanceTimersByTimeAsync(10_100);expect(screen.getByRole('heading',{name:'Current healthy state'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Pause guided mode'}));await vi.advanceTimersByTimeAsync(20_000);expect(screen.getByRole('heading',{name:'Current healthy state'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Restart guided mode'}));expect(screen.getByRole('heading',{name:'Problem'})).toBeTruthy();expect(fetchMock.mock.calls.every(([input])=>!String(input).match(/\/(approve|reject|request-evidence)$/))).toBe(true);vi.useRealTimers()});
 it('explains credential-dependent cloud services before showing honest evidence status',async()=>{history.replaceState({},'','/judge-demo?stage=google-cloud-evidence');vi.stubGlobal('fetch',mockJudgeFetch());wrap(<JudgeDemoPage/>);await screen.findByText(/Workflow 7/);expect(screen.getByText(/Explain the Google-native runtime architecture/)).toBeTruthy();expect(screen.getByText(/architectural value before seeing credential or access gaps/)).toBeTruthy();expect(screen.getByText(/GitHub OIDC environment secrets are currently missing/)).toBeTruthy();expect(screen.getAllByText('IMPLEMENTED_REQUIRES_CREDENTIALS').length).toBeGreaterThan(0);expect(screen.queryByText('VERIFIED_LIVE')).toBeNull()});
 it('orders purpose and implemented value before evidence status',async()=>{history.replaceState({},'','/judge-demo?stage=google-cloud-evidence');vi.stubGlobal('fetch',mockJudgeFetch());wrap(<JudgeDemoPage/>);const panel=await screen.findByRole('tabpanel');const text=panel.textContent??'';expect(text.indexOf('1. Purpose')).toBeLessThan(text.indexOf('4. What is already implemented'));expect(text.indexOf('4. What is already implemented')).toBeLessThan(text.indexOf('6. Current evidence status'));expect(text.indexOf('6. Current evidence status')).toBeLessThan(text.indexOf('15. Judge takeaway'))});
 it('uses non-animated scrolling when reduced motion is requested',async()=>{history.replaceState({},'','/judge-demo');const scroll=vi.fn();Object.defineProperty(HTMLElement.prototype,'scrollIntoView',{configurable:true,value:scroll});vi.stubGlobal('matchMedia',vi.fn(()=>({matches:true,media:'(prefers-reduced-motion: reduce)',addEventListener:vi.fn(),removeEventListener:vi.fn()})));vi.stubGlobal('fetch',mockJudgeFetch());wrap(<JudgeDemoPage/>);await screen.findByText(/Workflow 7/);fireEvent.click(screen.getByRole('tab',{name:/Rising Redis pressure/}));expect(scroll).toHaveBeenLastCalledWith(expect.objectContaining({behavior:'auto'}))});
});

function mockJudgeFetch(){return vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input);let data:unknown=[];if(url.endsWith('/api/v1/workflows'))data=[run];else if(url.includes('/api/v1/telemetry'))data=[{label:'now',minute:0,request_rate:1200,p50_ms:90,p95_ms:140,p99_ms:220,redis_cpu_pct:55,redis_memory_pct:72,cache_hit_rate_pct:91,queue_depth:2,application_replicas:4,error_rate_pct:.2,order_conversion_rate:.034,average_order_value_inr:3200,reactive_alert:false}];else if(url.endsWith('/evidence'))data=[{id:1,evidence_id:'ev-telemetry',category:'telemetry',source:'seed',observed_at:'2026-08-05',payload_json:{},summary:'Payment telemetry',content_hash:'c'.repeat(64)}];else if(url.endsWith('/timeline'))data=[{id:1,sequence:9,event_type:'state.recommended',actor:'executive-agent',payload_json:{trace_id:'trace-local'},previous_hash:'d'.repeat(64),event_hash:'e'.repeat(64),created_at:'2026-08-05'}];else if(url.endsWith('/verification'))data=[{result:'VERIFIED',checks:{audit_completeness:true},failed_checks:[],evidence_ids:['ev-gate'],audit_event_id:9}];else if(url.includes('/integrations/antigravity/status'))data={status:'BLOCKED_BY_PARTICIPANT_ACCESS',official_runtime_invoked:false,blocker:'Participant access unavailable',production_action:'NOT_EXECUTED'};else if(url.endsWith('/platform/integrations'))data=[{integration:'Gemini',status:'LOCAL_FALLBACK_AVAILABLE',fallback_status:'ACTIVE',configured_service:'gemini-2.5-flash',production_action:'NOT_EXECUTED'},{integration:'Cloud Run',status:'IMPLEMENTED_REQUIRES_CREDENTIALS',fallback_status:'NOT_INVOKED',configured_service:'cloud-run',production_action:'NOT_EXECUTED'}];else if(url.endsWith('/run-all')&&init?.method==='POST')data=run;return {ok:true,json:async()=>data} as Response})}
