import type {NexusCandidate} from '../../types';
import {STAGE_IDS,type DemoStatus,type IntegrationHealth,type JudgeStageId,type StageAdapterInput,type StageFact,type StageView} from './types';

const NA='NOT_YET_EXECUTED';
const text=(value:unknown,fallback=NA)=>value===undefined||value===null||value===''?fallback:String(value);
const shortHash=(value:unknown)=>text(value).length>20?`${text(value).slice(0,18)}…`:text(value);
const ids=(values:unknown):string[]=>Array.isArray(values)?values.map(String):[];
const record=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'?value as Record<string,unknown>:{};
const facts=(values:Record<string,unknown>):StageFact[]=>Object.entries(values).map(([label,value])=>({label:label.replaceAll('_',' '),value:text(value)}));

export function normalizeStatus(raw?:string,hasLocalEvidence=false):DemoStatus{
 const value=(raw??'').toUpperCase();
 if(value.includes('BLOCKED')||value.includes('ACCESS'))return 'BLOCKED_BY_PARTICIPANT_ACCESS';
 if(value.includes('FAIL'))return 'FAILED';
 if(value==='IMPLEMENTED_AND_VERIFIED'||value==='VERIFIED_LIVE')return 'VERIFIED_LIVE';
 if(value.includes('FALLBACK')||value.includes('LOCAL_ADAPTER'))return 'FALLBACK_ACTIVE';
 if(value.includes('REQUIRES_CREDENTIALS'))return 'REQUIRES_CREDENTIALS';
 return hasLocalEvidence?'VERIFIED_LOCAL':'NOT_YET_EXECUTED';
}

export function buildJudgeStages(input:StageAdapterInput):StageView[]{
 const {run}=input; const forecast=record(run?.forecast_json); const twin=record(run?.twin_json); const impact=record(run?.impact_json); const recommendation=record(run?.recommendation_json);
 const scenarios=run?.scenarios_json??[]; const candidates=run?.tournament_json?.candidates??[]; const winner=candidates.find(candidate=>candidate.candidate_id===run?.tournament_json?.recommended_candidate_id); const fast=candidates.find(candidate=>candidate.candidate_id==='fast');
 const latestTelemetry=input.telemetry?.at(-1); const latestAudit=input.audit?.at(-1); const verification=input.verification?.at(0); const integration=(name:string)=>input.integrations?.find(row=>row.integration.toLowerCase().includes(name.toLowerCase()));
 const local=(ready:boolean):DemoStatus=>input.failed?'FAILED':input.loading?'NOT_YET_EXECUTED':ready?'VERIFIED_LOCAL':'NOT_YET_EXECUTED';
 const managed=(row?:IntegrationHealth)=>normalizeStatus(row?.status,Boolean(row?.last_successful_call));
 const evidenceIds=ids(forecast.evidence_ids); const trace=(row?:IntegrationHealth)=>text(row?.trace_id); const candidateFacts=(candidate?:NexusCandidate):StageFact[]=>candidate?[
  {label:'Candidate',value:candidate.name,emphasis:candidate.eligible?'good':'bad'},{label:'Score',value:String(candidate.score)},{label:'Risk',value:`${candidate.risk_score}/100`},{label:'Cost',value:`INR ${candidate.cost_estimate_inr.toLocaleString('en-IN')}`},{label:'Recovery',value:`${candidate.recovery_minutes} min`},{label:'Eligibility',value:candidate.eligible?'ELIGIBLE':'DISQUALIFIED',emphasis:candidate.eligible?'good':'bad'}
 ]:[];
 const base=(id:JudgeStageId,title:string,shortTitle:string,summary:string,why:string,status:DemoStatus,outputs:StageFact[],safetyRule:string,googleService:string,takeaway:string,extra:Partial<StageView>={}):StageView=>({
  id,number:STAGE_IDS.indexOf(id)+1,title,shortTitle,summary,why,status,inputs:[],outputs,evidenceIds:[],resultHash:NA,traceId:NA,latency:NA,safetyRule,googleService,fallbackState:status==='VERIFIED_LOCAL'?'FALLBACK_ACTIVE':status,takeaway,nextStage:STAGE_IDS[STAGE_IDS.indexOf(id)+1]?.replaceAll('-',' ')??'Complete',...extra
 });

 return [
  base('telemetry','Telemetry Ingestion','Telemetry','Validated Payment Service signals enter the evidence boundary.','Prediction is useful only when its source measurements are visible, recent, and attributable.',local(Boolean(latestTelemetry)),facts({redis_memory_pct:latestTelemetry?.redis_memory_pct!=null?`${latestTelemetry.redis_memory_pct}%`:undefined,traffic_rate:latestTelemetry?.request_rate,error_rate:latestTelemetry?.error_rate_pct!=null?`${latestTelemetry.error_rate_pct}%`:undefined,reactive_alert:latestTelemetry?.reactive_alert}), 'Invalid or missing telemetry blocks downstream reasoning.','Cloud Run API · BigQuery analytical export', 'The alert can still look healthy while Redis pressure is already measurable.',{inputs:facts({workflow_id:run?.id,source:'Payment Service telemetry'}),evidenceIds:input.evidence?.filter(e=>e.category==='telemetry').map(e=>e.evidence_id)??[],resultHash:shortHash(input.evidence?.find(e=>e.category==='telemetry')?.content_hash),telemetry:latestTelemetry,evidence:input.evidence}),
  base('forecast','Redis Forecast Service','Forecast','A bounded linear model forecasts Redis safe-capacity crossing.','It creates intervention time before a reactive customer-impact alert.',local(Boolean(forecast.predicted_crossing_minutes)),facts({current_memory:latestTelemetry?.redis_memory_pct!=null?`${latestTelemetry.redis_memory_pct}%`:undefined,equation:forecast.equation,safe_threshold:forecast.safe_threshold_pct!=null?`${forecast.safe_threshold_pct}%`:undefined,predicted_crossing:`+${text(forecast.predicted_crossing_minutes)} min`,customer_impact:`+${text(forecast.predicted_customer_impact_minutes)} min`,residual_mae:forecast.residual_mae,error_bound:`±${text(forecast.error_bound_minutes)} min`}), 'The deterministic forecast remains authoritative; managed AI cannot alter it.','Cloud Run forecast service · Gemini Enterprise supplemental analysis', 'The canonical seed crosses safe capacity at +30 minutes and estimates customer impact at +45 minutes.',{inputs:facts({observation_window:forecast.observation_window,model:forecast.model_name}),evidenceIds,resultHash:shortHash(forecast.output_hash),fallbackState:'FALLBACK_ACTIVE'}),
  base('digital-twin','Digital Twin Engine','Digital Twin','A version-locked, network-disabled model bounds every replay.','Hashes, a fixed seed, and explicit assumptions make scenario comparison reproducible.',local(Boolean(twin.manifest_hash)),facts({manifest_version:twin.source_revision,twin_id:twin.twin_id,manifest_hash:shortHash(twin.manifest_hash),topology:'checkout-api → payment-service → redis-primary',network_policy:twin.network_policy,seed:twin.random_seed}), 'The Twin cannot access or modify production infrastructure.','Cloud Run orchestrator · Secret Manager configuration', 'This is a bounded operational model, not an uncontrolled production replica.',{inputs:facts(record(twin.capacity_constraints)),outputs:facts({allowed_scenarios:Array.isArray(twin.allowed_scenarios)?twin.allowed_scenarios.length:undefined,assumption:twin.limitation}),evidenceIds:ids(twin.evidence_references),resultHash:shortHash(twin.manifest_hash)}),
  base('simulation','Simulation Engine','Simulation',`${scenarios.length} of 12 deterministic counterfactuals are persisted.`,'Twelve comparable futures expose failure modes before an operator chooses an intervention.',local(scenarios.length===12),facts({progress:`${scenarios.length}/12`,latest_scenario:scenarios.at(-1)?.name,p95_latency:scenarios.at(-1)?.p95_ms!=null?`${scenarios.at(-1)?.p95_ms} ms`:undefined,error_rate:scenarios.at(-1)?.error_rate_pct!=null?`${scenarios.at(-1)?.error_rate_pct}%`:undefined,recovery:scenarios.at(-1)?.recovery_minutes!=null?`${scenarios.at(-1)?.recovery_minutes} min`:undefined}), 'Scenario execution is sandboxed and network-disabled.','Cloud Run simulation service · Pub/Sub event boundary', 'The UI reports persisted scenario results; its progress animation never invents completion.',{inputs:facts({twin_id:run?.tournament_json?.twin_id,seed:run?.seed}),evidenceIds:scenarios.flatMap(s=>s.evidence_ids),resultHash:shortHash(scenarios.at(-1)?.result_hash),scenarios}),
  base('optimization','Optimization Engine','Optimization','FAST, SAFE, and OPTIMAL compete under transparent scoring.','Operators see benefit, cost, risk, recovery, reversibility, and eligibility together.',local(candidates.length===3),candidateFacts(winner), 'Mandatory eligibility gates override score.','Cloud Run orchestrator', 'OPTIMAL is recommended only when it is the highest-scoring eligible candidate.',{inputs:facts(run?.tournament_json?.weights??{}),outputs:[...candidateFacts(fast),...candidateFacts(winner)],resultHash:shortHash(run?.tournament_json?.twin_id),candidates}),
  base('gemini','Gemini Reasoning','Gemini','Gemini synthesizes evidence, contradictions, and recommendation context.','AI turns structured results into an auditable explanation while deterministic services retain authority.',managed(integration('gemini')),facts({prompt_id:integration('gemini')?'evidence-reasoning-v1':undefined,prompt_version:'v1',model:integration('gemini')?.configured_service,reasoning_summary:recommendation.summary,trace_id:integration('gemini')?.trace_id}), 'Gemini cannot calculate gates, approve, mutate state, or execute production actions.','Google AI Studio → Prompt Management → Prompt Evaluation → Gemini Runtime', 'AI explains the evidence; it does not own the decision.',{inputs:facts({evidence_count:evidenceIds.length}),evidenceIds:ids(recommendation.evidence_ids),resultHash:shortHash(recommendation.output_hash),traceId:trace(integration('gemini')),latency:NA,fallbackState:normalizeStatus(integration('gemini')?.fallback_status)}),
  base('gemma','Gemma Policy Review','Gemma','Gemma performs a secondary, advisory-only policy critique.','A separate review catches contradictions and recommendation-to-gate inconsistencies.',managed(integration('gemma')),facts({policy_result:integration('gemma')?.last_successful_call?'CONSISTENCY REVIEWED':undefined,evidence_completeness:ids(recommendation.evidence_ids).length?'EVIDENCE LINKED':undefined,advisory_only:'YES',trace_id:integration('gemma')?.trace_id}), 'Gemma cannot override gates, approve, mutate state, or execute production actions.','Gemma Private Policy Review Engine on Cloud Run', 'A second model may critique policy, but backend gates remain final.',{evidenceIds:ids(recommendation.evidence_ids),traceId:trace(integration('gemma')),fallbackState:normalizeStatus(integration('gemma')?.fallback_status)}),
  base('safety-gates','Mandatory Safety Gates','Safety Gates','Deterministic policy makes FAST failure explicit and decides eligibility.','A plausible high-speed fix is rejected when failover safety fails.',local(candidates.length>0),facts({fast:fast?.eligible?'ELIGIBLE':'DISQUALIFIED',fast_failure:fast?.gates.find(g=>!g.passed)?.gate,rule:run?.tournament_json?.rule,recommended:winner?.name}), 'One failed mandatory gate disqualifies a candidate regardless of score.','Backend policy service on Cloud Run', 'FAST fails; eligibility—not presentation or model preference—controls the tournament.',{inputs:candidates.flatMap(c=>c.gates).map((g):StageFact=>({label:g.gate,value:g.passed?'PASS':'FAIL',emphasis:g.passed?'good':'bad'})),candidates,evidenceIds:candidates.flatMap(c=>c.gates.flatMap(g=>g.evidence_ids))}),
  base('verification','Verification Agent','Verification','Technical and approver-readiness checks are persisted.','Verification ensures evidence, audit, gates, replay, and the disabled production boundary are ready before a human sees approval.',local(Boolean(verification)||run?.state==='AWAITING_HUMAN'||run?.state==='DECIDED'),facts({verification_result:record(verification).result??(run?.state==='AWAITING_HUMAN'||run?.state==='DECIDED'?'VERIFIED':undefined),failed_checks:Array.isArray(record(verification).failed_checks)?(record(verification).failed_checks as unknown[]).join(', ')||'NONE':undefined,evidence_complete:record(verification).checks?'CHECKED':undefined}), 'The Verification Agent verifies; it never approves.','Cloud Run verification service', 'Verification establishes readiness, not authority.',{inputs:facts(record(record(verification).checks)),evidenceIds:ids(record(verification).evidence_ids),resultHash:shortHash(record(verification).audit_event_id)}),
  base('executive','Executive Recommendation','Executive','The highest-scoring eligible candidate is explained with business impact.','Decision-makers receive a concise recommendation, rejected alternatives, uncertainty, and exposure assumptions.',local(Boolean(recommendation.recommendation)),facts({selected_candidate:winner?.name,recommendation:recommendation.recommendation,business_exposure:impact.revenue_exposure_inr!=null?`INR ${Number(impact.revenue_exposure_inr).toLocaleString('en-IN')}`:undefined,recovery:impact.estimated_recovery_minutes!=null?`${impact.estimated_recovery_minutes} min`:undefined,rejected_alternative:fast?.verdict}), 'The Executive Agent has no approval authority.','Gemini Runtime · Cloud Run API', 'Recommendation is evidence-backed advice, not an automated change.',{inputs:facts({contradictory_evidence:Array.isArray(recommendation.contradictory_evidence)?recommendation.contradictory_evidence.join('; '):undefined}),evidenceIds:ids(recommendation.evidence_ids)}),
  base('awaiting-human','AWAITING_HUMAN','Awaiting Human','Automation stops at the governed human boundary.','The explicit state makes the remaining authority visible and prevents silent automation.',local(run?.state==='AWAITING_HUMAN'||run?.state==='DECIDED'),facts({workflow_state:run?.state,eligible_candidate:winner?.eligible?'YES':'NO',mandatory_gates:winner?.gates.every(g=>!g.mandatory||g.passed)?'PASS':'NOT READY',required_checks:'Verified role · eligible candidate · rationale'}), 'No model, agent, or MCP tool may cross this boundary.','Backend workflow authority on Cloud Run', 'The system deliberately stops where accountable human judgment begins.',{href:run?`/workflows/${run.id}/approval`:'/command-centre'}),
  base('human-approval','Human Approval','Approval','Backend RBAC verifies the human role and mandatory rationale.','Interns can inspect and simulate but cannot approve; Senior Developers still need a short-lived token and rationale.',local(run?.state==='DECIDED'),facts({intern_approval:'HTTP 403 · APPROVER_NOT_QUALIFIED',senior_requirement:'Verified role token + rationale',decision:record(run?.human_decision_json).decision,actor:record(run?.human_decision_json).actor_name}), 'Approval records a decision only. No approval is ever submitted by this demo.', 'JWT · backend RBAC · Cloud Run API', 'Human approval enables evidence export; it never deploys, scales, or reconfigures.',{href:run?`/workflows/${run.id}/approval`:'/command-centre',fallbackState:run?.state==='DECIDED'?'VERIFIED_LOCAL':'NOT_YET_EXECUTED'}),
  base('audit-chain','Tamper-Evident Audit Chain','Audit Chain','Every governed event links its SHA-256 hash to the previous event.','Hash linkage makes later alteration detectable and ties decisions to evidence and traces.',local(Boolean(latestAudit)),facts({chain_position:latestAudit?.sequence,event_id:latestAudit?.id,event_type:latestAudit?.event_type,previous_hash:shortHash(latestAudit?.previous_hash),current_hash:shortHash(latestAudit?.event_hash),actor:latestAudit?.actor}), 'Audit evidence is append-only through the application boundary; no “immutable” claim is made.', 'Cloud Run evidence service · BigQuery analytical export', 'The chain provides tamper evidence from creation through human governance.',{audit:latestAudit,evidenceIds:ids(latestAudit?.payload_json?.evidence_references),resultHash:shortHash(latestAudit?.event_hash),traceId:text(latestAudit?.payload_json?.trace_id)}),
  base('evidence-zip','Evidence ZIP','Evidence ZIP','A governed decision unlocks a verifiable evidence package.','The ZIP joins forecast, Twin, scenarios, gates, decision, audit events, and manifest.sha256 for independent review.',run?.state==='DECIDED'?'VERIFIED_LOCAL':'NOT_YET_EXECUTED',facts({availability:run?.state==='DECIDED'?'AVAILABLE':'LOCKED UNTIL DECISION',manifest:'manifest.sha256',audit_events:input.audit?.length,verification:run?.state==='DECIDED'?'READY FOR DOWNLOAD VERIFICATION':undefined}), 'Export reads evidence only and is revoked after one download; it never executes production actions.','Cloud Run evidence service · Cloud Storage boundary', 'A judge can inspect and verify the result package after human governance.',{href:run?`/workflows/${run.id}/export`:undefined,evidenceIds:input.evidence?.map(e=>e.evidence_id)??[]}),
  base('google-cloud','Google Cloud Evidence','Google Cloud','Managed-runtime evidence is displayed only when backend integration health confirms it.','This stage is retained to distinguish the production hosting target from separately authenticated data, event, model, identity, and observability services. Cloud deployment and individual integrations are separate claims; one never upgrades the other.',managed(integration('cloud run')),facts({purpose:'Prove hosting, build provenance, managed data and event flow, IAM, secrets, and traces independently',cloud_run_service_count:integration('cloud run')?.last_successful_call?'9':undefined,latest_revision:NA,cloud_build_id:NA,artifact_registry_image:NA,bigquery_row_id:NA,pubsub_message_id:NA,cloud_trace_id:integration('open')?.trace_id,secret_manager:normalizeStatus(integration('secret')?.status),a2a_messages:input.a2a?.length??0,antigravity:input.antigravity?.status}), 'IAM/service identities, managed data calls, and traces require their own evidence.','Cloud Build → Artifact Registry → Cloud Run · BigQuery · Pub/Sub · Secret Manager · Operations Suite', 'Unavailable cloud IDs remain explicit; the deterministic local product still works without them.',{inputs:[{label:'Why retained',value:'Makes credential-dependent runtime proof auditable without presenting fallback output as managed-cloud success'},...(input.integrations??[]).map(row=>({label:row.integration,value:normalizeStatus(row.status,Boolean(row.last_successful_call))}))],traceId:trace(integration('open')),fallbackState:managed(integration('cloud run'))})
 ];
}
