from enum import StrEnum

class AgentState(StrEnum):
    NEW="NEW"; ALERT_RECEIVED="ALERT_RECEIVED"; COLLECTING_EVIDENCE="COLLECTING_EVIDENCE"; EVIDENCE_READY="EVIDENCE_READY"
    GENERATING_HYPOTHESES="GENERATING_HYPOTHESES"; HYPOTHESES_READY="HYPOTHESES_READY"; REPRODUCING="REPRODUCING"
    REPRODUCTION_CONFIRMED="REPRODUCTION_CONFIRMED"; REPRODUCTION_FAILED="REPRODUCTION_FAILED"; GENERATING_PATCH="GENERATING_PATCH"
    PATCH_READY="PATCH_READY"; VERIFYING="VERIFYING"; VERIFICATION_PASSED="VERIFICATION_PASSED"; VERIFICATION_FAILED="VERIFICATION_FAILED"
    AWAITING_APPROVAL="AWAITING_APPROVAL"; APPROVED="APPROVED"; REJECTED="REJECTED"; PR_CREATED="PR_CREATED"; ESCALATED="ESCALATED"; COMPLETED="COMPLETED"

TRANSITIONS = {
 AgentState.NEW:{AgentState.ALERT_RECEIVED}, AgentState.ALERT_RECEIVED:{AgentState.COLLECTING_EVIDENCE}, AgentState.COLLECTING_EVIDENCE:{AgentState.EVIDENCE_READY,AgentState.ESCALATED},
 AgentState.EVIDENCE_READY:{AgentState.GENERATING_HYPOTHESES}, AgentState.GENERATING_HYPOTHESES:{AgentState.HYPOTHESES_READY,AgentState.ESCALATED}, AgentState.HYPOTHESES_READY:{AgentState.REPRODUCING},
 AgentState.REPRODUCING:{AgentState.REPRODUCTION_CONFIRMED,AgentState.REPRODUCTION_FAILED}, AgentState.REPRODUCTION_CONFIRMED:{AgentState.GENERATING_PATCH}, AgentState.REPRODUCTION_FAILED:{AgentState.ESCALATED},
 AgentState.GENERATING_PATCH:{AgentState.PATCH_READY,AgentState.ESCALATED}, AgentState.PATCH_READY:{AgentState.VERIFYING}, AgentState.VERIFYING:{AgentState.VERIFICATION_PASSED,AgentState.VERIFICATION_FAILED},
 AgentState.VERIFICATION_PASSED:{AgentState.AWAITING_APPROVAL}, AgentState.VERIFICATION_FAILED:{AgentState.GENERATING_PATCH,AgentState.ESCALATED}, AgentState.AWAITING_APPROVAL:{AgentState.APPROVED,AgentState.REJECTED},
 AgentState.APPROVED:{AgentState.PR_CREATED}, AgentState.PR_CREATED:{AgentState.COMPLETED}, AgentState.REJECTED:{AgentState.COMPLETED}, AgentState.ESCALATED:{AgentState.COMPLETED}, AgentState.COMPLETED:set()
}
class InvalidTransition(ValueError): pass
def validate_transition(current: AgentState, target: AgentState) -> None:
    if target not in TRANSITIONS[current]: raise InvalidTransition(f"Invalid transition: {current} -> {target}")
