CREATE TABLE IF NOT EXISTS `${PROJECT}.${DATASET}.telemetry_events` (event_id STRING, workflow_id INT64, observed_at TIMESTAMP, payload JSON) PARTITION BY DATE(observed_at) CLUSTER BY workflow_id;
CREATE TABLE IF NOT EXISTS `${PROJECT}.${DATASET}.workflow_events` (event_id STRING, workflow_id INT64, event_type STRING, created_at TIMESTAMP, payload JSON) PARTITION BY DATE(created_at) CLUSTER BY workflow_id, event_type;
CREATE TABLE IF NOT EXISTS `${PROJECT}.${DATASET}.agent_executions` (execution_id STRING, workflow_id INT64, agent_name STRING, duration_ms INT64, created_at TIMESTAMP, payload JSON) PARTITION BY DATE(created_at) CLUSTER BY workflow_id, agent_name;
CREATE TABLE IF NOT EXISTS `${PROJECT}.${DATASET}.scenario_results` (result_id STRING, workflow_id INT64, scenario_id STRING, created_at TIMESTAMP, payload JSON) PARTITION BY DATE(created_at) CLUSTER BY workflow_id, scenario_id;
CREATE TABLE IF NOT EXISTS `${PROJECT}.${DATASET}.verification_results` (verification_id STRING, workflow_id INT64, result STRING, created_at TIMESTAMP, payload JSON) PARTITION BY DATE(created_at) CLUSTER BY workflow_id, result;
CREATE TABLE IF NOT EXISTS `${PROJECT}.${DATASET}.model_invocations` (invocation_id STRING, workflow_id INT64, model STRING, latency_ms INT64, created_at TIMESTAMP, payload JSON) PARTITION BY DATE(created_at) CLUSTER BY workflow_id, model;
CREATE TABLE IF NOT EXISTS `${PROJECT}.${DATASET}.business_impact_estimates` (estimate_id STRING, workflow_id INT64, created_at TIMESTAMP, payload JSON) PARTITION BY DATE(created_at) CLUSTER BY workflow_id;
CREATE TABLE IF NOT EXISTS `${PROJECT}.${DATASET}.audit_event_exports` (event_id STRING, workflow_id INT64, event_hash STRING, created_at TIMESTAMP, payload JSON) PARTITION BY DATE(created_at) CLUSTER BY workflow_id;
CREATE TABLE IF NOT EXISTS `${PROJECT}.${DATASET}.forecast_evaluations` (evaluation_id STRING, workflow_id INT64, model STRING, variance FLOAT64, created_at TIMESTAMP, payload JSON) PARTITION BY DATE(created_at) CLUSTER BY workflow_id, model;
